### ISSUE TITLE
Tooltip for add keymap

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#102]

**Comment by mondalaci** [comment]
UI Fixes:

* Let's place the tooltip below the key, just like for the key action popover.
* Ideally, the tip of the tooltip should point right to the edge of the key, not inside of it.
* Right now, if I move the pointer from the key to the tooltip quickly, the tooltip stays there instead of showing a new tooltip for the key at the pointer.

Textual fixes:

It'd be great to "humanize" the text, so that it'd be more readable to users.

* Instead of writing "KeyAction: SwitchLayerAction" let's write "Action type: Switch layer", and same deal for other key actions
* Instead of writing "Scancode: 4" let's write "Scancode: 4 (A)"

**Comment by mondalaci** [comment]
The current tooltip also has the tendency of staying in place even if I scroll a long way. I'm not sure whether these issues can be solved with the current tooltip component / library but if not, possibly a more responsive tooltip library should be choosen.
