### ISSUE TITLE
Macro UI improvements

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#108]
Please let me propose a couple of improvements to the macro UI:
- Minimize the width of the 1st and 2nd columns of the macro action editor and maximize the width of the 3rd column. If only 2 columns are involved then minimize the width of the 1st and maximize the 2nd. This way the layout would work better on smaller width displays.
- Use `pointer` cursor type over the whole macro action title bar.
- The former point makes the pen icon quite redundant, so it'd make sense to remove it.

**Comment by fjozsef** [comment]
@mondalaci  What do you think about closing the macro editor (like the cancel) when clicking on macro-item (like how you opened it)? It would provide fast closing possibility for accidental openings.

**Comment by mondalaci** [comment]
@fjozsef I agree that clicking on a non-active macro action or on the title of the active macro action should cancel the editing of the current macro action.

**Comment by fjozsef** [comment]
I am talking about canceling the editing of the current one.

**Comment by mondalaci** [comment]
Gotcha. I think the two cases that I mentioned includes yours, too. We should still keep the cancel button despite its redundancy because it's the most intuitive way to cancel the editing of the current macro action.

**Comment by fjozsef** [comment]
I agree.

**Comment by NejcZdovc** [comment]
@mondalaci can you please check this issue and see what still needs to be done.

**Comment by mondalaci** [comment]
@NejcZdovc Sure thing! It seems to me that the column width issue still stands, the pointer cursor has been resolved, and according to my memory we discussed in the meantime that we should keep the pen icon.

**Comment by laxu** [comment]
Would this be an acceptable solution to the width issue? Basically on small window sizes turn the first section into a vertical list and in anything larger it shows as before. Otherwise you will run into issues that can only be solved by making the left sidebar hidden in small screens and only shown with some toggle button.

<img width="433" alt="uhk-macro-editor-suggestion" src="https://cloud.githubusercontent.com/assets/987972/26556051/ebb5e4ec-44a0-11e7-86d9-a902ac908955.png">

PS. Sorry for having had no time to work on this project.

**Comment by attilacsanyi** [comment]
I would recommend to use **angular** [flex-layout](https://github.com/angular/flex-layout) elegant library to _handle layout changes based on specific screen sizes_.

**Comment by laxu** [comment]
Bootstrap grid system already handles resizing the layout just fine. It's mainly the design of the macro editor that is a bit problematic with the arrows that overlap the next section etc. 

One issue is that SCSS version of boostrap is not used and thus its variables cannot be loaded in SCSS files.

**Comment by mondalaci** [comment]
I'd also rather stick to the Bootstrap grid unless Angular flex-layout offers some definitive advantage over it.

That being said, I'm not really concerned about responsive layout at this point. The whole Agent UI assumes that there's plenty of space available, at least about 1024x786. I believe it'd make sense to focus on standing issues right now, and eventually make the UI more responsive.

**Comment by mondalaci** [comment]
@attilacsanyi This looks like yet another great introductory issue for you. :) You're welcome to ask if you have any questions.

**Comment by attilacsanyi** [comment]
I did couple of changes and also use @laxu solution above.
_(Now I see bootstrap css classes are very limited in order to make proper responsive behaviour even pragmatically.)_

**Changes**

**1.** use pointer cursor over macro title bar
**2.** macro title bar is always clickable and can also be used for exit from edit mode
**3.** small responsive behaviour in the macro layout and column sizing

@mondalaci let me know your comments, please checkout `issue-108` branch.

**Comment by mondalaci** [comment]
@attilacsanyi Well done, thank you! I've just merged your branch to master. Next time, please send me a PR, so that I'll be able to merge even easier.

**Comment by attilacsanyi** [comment]
Cool I am happy if you are happy :) going to do always PR when I assume its done @mondalaci
