### ISSUE TITLE
Support for non-tilted view of keyboard halves.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1097]
Hi. Long story short - tilted view is annoying and hard to read. Could the halves be simply shown split without tilting? Or could it be added as an option in settings?

**Comment by mondalaci** [comment]
There are two details that contribute to harder readability. The first is the angled view of the halves, and the second is the distance between the halves. The first is more prevalent when it comes to readability, especially on lower DPI displays.

In order to maximize readability, the halves should be dispalyed as merged even when they're split. This is feasible usability-wise when no modules are attached.

This is one of those cases for which we could just add an option as suggested. However, every single option complicates the UI just a little bit, and I expect HDPI screens to gain more foothold over time, so I'd rather not add an option for this for the time being. If this becomes a more popular issue, I'll reconsider.

**Comment by parke** [comment]
I second this feature request.

I typically use my UHK split, but on my 1280 x 1024 display, it is **much** easier to read the displayed keyboard when the halves are merged together.  There are many 1280 wide displays, as this is the width of 720p displays.  I don't use any modules, so I can just plug the halves together.  However, I would still prefer to have an option to "Always display keyboard halves joined together."

As for this complicating the UI...  the Agent -> Settings page is currently pretty barren.  It has three options.  Adding a fourth option to the settings page seems very feasibly and would only add minimal complication to the UI, in my opinion.

As for the wording of the option, it could either be:

1)  A checkbox, defaults unchecked, with the wording:  "Always display keyboards halves joined together."

2) A select (popup) menu:  "Display keyboard halves: [ Auto | Joined | Split ]"

Or perhaps there is a better way to phrase the setting text.

**Comment by mondalaci** [comment]
We can add an option to show the halves non-tilted, but only if the modules are unattached. Sounds good?

**Comment by parke** [comment]
> We can add an option to show the halves non-tilted, but only if the modules are unattached. Sounds good?

Yes please.
