### ISSUE TITLE
[feature request] store keymap configs in a file format that allows comments

### ISSUE THREAD

**Issue by maplebed** [UltimateHackingKeyboard/agent#115]
The current format for storing keymaps is JSON. While easy to parse and write from code, it is not easy to manipulate by hand, and it prohibits comments. When making complex layouts or sharing keymaps with the community, it would be nice to be able to comment the layout, describing more complex functions and annotating scancodes with actual character values. Additionally, when developing new keymaps, it is helpful to be able to comment out sections while doing experiments.

I believe the most obvious alternatives to JSON are YAML or TOML (or ::shudder:: XML). 

With any of these formats, a story for how to preserve comments when making changes to the keymap via the GUI will need to be addressed.

**Comment by mondalaci** [comment]
JSON has been chosen as our data serialization format because Agent builds upon the web stack, and as such, it's the easiest and most natural format to work with.

I understand your use case, but keymaps are not primarily meant to be edited by hand. As for sharing, we will implement features in Agent to make creating, modifying, and sharing keymaps a breeze. As for commenting, it'll be possible to add comments in Agent on a per keymap basis.

Given the above, implementing additional data serialization formats would incur a significant maintenance burden for little benefit.

I'm closing this as wontfix. If you have any further questions, you're welcome to ask.
