### ISSUE TITLE
Feature: Import & Export keymaps

### ISSUE THREAD

**Issue by Siebjee** [UltimateHackingKeyboard/agent#1190]
It would be nice to have the option to share keymaps or import other keymaps.
For instance, i've deleted the default ones, but want to tryout Dovorak. Now i need to create one myself. Where if i could download the default dovorak for UHK i could import it.

**Comment by kareltucek** [comment]
Regarding your exact usecase - you can backup your full configuration via Agent and then reset it to default, which should give you back the default Dvorak. (Then you can keep the default or import the backup again.) In case you actually need to move just one keymap, you can do it manually - the json files are written in a quite intuitive human-readable format, so you can port a keymap via text editor.

Generally, I can only agree. UHK lacks means of sharing user configs/knowledge, more specifically the import/export of a single keymap (which I guess is complicated because of macros) and a place to do so (e.g., a forum).

**Comment by Siebjee** [comment]
Gist is a good place to do so or stack overflow, github issues. Plus Google searches are quite well indexed for this case (maybe?). But the fact that I can import and export my whole configuration, reset it and hack the hacking keyboard is not so much user friendly. 

However I'm willing to try it, but where to hack?

**Comment by kareltucek** [comment]
> However I'm willing to try it, but where to hack?

Open agent, click Configuration (under "Device" section at the top), and there you go - exporting the device configuration will yield a json file.

**Comment by Siebjee** [comment]
I managed to do this, but i had to remove the used macro bindings first. Else the configuration was invalid (without error details).

**Comment by mondalaci** [comment]
Closing this issue as it's a duplicate of #459.
