### ISSUE TITLE
Improve dropdown item layout

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#1219]
Please add about 5px top margin or padding to the dropdown items of the layer tab of the key action popover.

![image](https://user-images.githubusercontent.com/300402/79622694-9065a480-8118-11ea-820f-8983b8b978fd.png)

Maybe it'd also be worth to subtract about 5px bottom margin or padding from the dropdown items to make the space between the items the same as it is.

**Comment by ert78gb** [comment]
Yes because it is a native select component and rendered by the browser.
The rendered version on Mac
<img width="594" alt="Screenshot 2020-04-23 at 21 49 26" src="https://user-images.githubusercontent.com/496775/80143616-61827f00-85ad-11ea-9d41-bba2d596c69d.png">

Maybe we can use the same component that we use in the keypress tab.
What do you think?

**Comment by mondalaci** [comment]
I agree. Let's use select2 here, too.
