### ISSUE TITLE
Shell integration

### ISSUE THREAD

**Issue by ihomam** [UltimateHackingKeyboard/agent#1268]
Is there a way to change the activated layer from terminal?
I built agent on my machine and tried to find how layers are getting changed but I didn't succeed. 

What I'm trying to do is to switch between layers from gaming car pedals :D

**Comment by mondalaci** [comment]
Yours is quite an interesting use case :)

I'm sorry but layers can't be changed from the terminal. Only keycaps can be changed [this way](https://github.com/UltimateHackingKeyboard/agent/blob/d148ca46ebb53cb731e1a74cf06b5bd715d2d10b/packages/usb/switch-keymap.js).

**Comment by kareltucek** [comment]
> I built agent on my machine and tried to find how layers are getting changed but I didn't succeed.

However, this should not be hard to implement - if you are as far as having the agent built... If you need some hints w.r.t. the firmware, feel free to open a ticket at https://github.com/kareltucek/firmware .

I am just a bit concerned about actual latency - I am not sure how fast the js/agent can react...

**Comment by ihomam** [comment]
Thx guys! 

@kareltucek I agree with you, I checked your firmware in the morning. I think I can use `COMMAND = toggleLayer LAYERID`! 

Now i have 2 approaches to test, yay. Will check and try!

**Comment by kareltucek** [comment]
Well, it will be much more straightforward to create a new usb command specifically for the layer toggle and connect it to the standard layer switching mechanism, e.g. LayerSwitcher_ToggleLayer (etc)... 

Of course sending an entire command via usb is a nice idea, but connecting it to the macro engine might be complicated.

**Comment by ihomam** [comment]
I have no clue what is standard layer switching mechanism, usb command nor macro engine :D 

I'm hoping to write a small program on my mac to intercept pedal events: 
- left pedal event would be altered to double `shift` for example. then make double shift = change to mouse layer on uhk.
- right pedal event would be altered to double `ctrl`. double `ctrl` changes to mod layer.

That was my idea at the beginning, I checked  https://github.com/kareltucek/firmware and I'm not sure if I can trigger a macro from a double shift :D 
I think the uhk keyboard doesn't care what's happening on the system in the first place! isn't it right? double shift wouldn't trigger anything if it's not triggered from uhk.

**Comment by kareltucek** [comment]
Well...

- Macro engine is the thing implemented in `(firmware)/right/src/macros.c` which interprets macros (those you see in Agent), and you probably want to avoid it. In that case you also want to avoid my fork and its commands entirelly, because they are implemented as an extension of the macro engine. 
- Regarding the fork - there is no need to use it in order to implement the pedal controls.
- Standard layer switching mechanism is the thing you will find in `right/src/layer_switcher.c`. It takes care of switching layers.

-------

> I think the uhk keyboard doesn't care what's happening on the system in the first place! isn't it right? 

Yes, that is right, and that is exactly why you will need to create a custom USB command in order to trigger anything from your system. 

There already exists the command/script to switch keymaps (as Laci mentioned above) [here](https://github.com/UltimateHackingKeyboard/agent/blob/d148ca46ebb53cb731e1a74cf06b5bd715d2d10b/packages/usb/switch-keymap.js), and on the firmware side, it ends up in [right/src/usb_commands/usb_command_switch_keymap.c](https://github.com/UltimateHackingKeyboard/firmware/blob/master/right/src/usb_commands/usb_command_switch_keymap.c). It should suffice to follow (and duplicate) that implementation on both sides (agent and firmware), and then connect it to some of the functions in `layer_switcher.c` (on firmware side). Then you should be able to toggle/untoggle layers by executing a script in your system. And hooking that to your pedals should be a piece of cake.

**Comment by mondalaci** [comment]
I planned to implement layer state sync anyway, so this is the best place to share my thoughts after all, even though it's far down the road.

Eventually, I plan to release additional UHK input devices, such as a numeric keypad. Usability-wise, it'll be useful to sync layer state across these devices which will be implemented via the UHK USB protocol as suggested by Karel. In such a scenario, Agent will act as a proxy to propagate layer state to multiple USB devices, all relying on the UHK USB protocol.

As for the protocol, both a setter and a getter USB protocol command must be implemented to make this work. The getter is already implemented which can be tested via `packages/usb/get-device-state.js`. The setter has yet to be implemented.

This being a peer to peer scheme, conflicts can occur. Imagine hitting different layer switcher keys on multiple devices at the same time. The way to resolve this for Agent is to force the layer of the master device (the first device that switched away from the base layer from the standpoint of Agent) until the layer is released on the master. For toggle layer actions, it should be possible to untoggle the layer by any device.

I'm not sure the above is useful because the above use case is quite specific, but I wanted to dump my mind, so it'll be easier to pick up layer state sync when the time comes.
