### ISSUE TITLE
Feature request: tap-and-hold

### ISSUE THREAD

**Issue by pbartyik** [UltimateHackingKeyboard/agent#1286]
I'm a heavy terminal user, would like to stay more on the home row.
I would like to have the ability to bind modifiers (CTRL ALT SHIFT SUPER) or layer switchers (FN MOD MOUSE) as tap-and-hold keys.
This would mean that a single key could be mapped in four ways:
Primary (basic tap)
Secondary (hold)
Double-tap (can't wait for #720 )
Tap-and-hold (this one)

Primary and double-tap would emit scan codes, secondary and tap-and-hold would activate modifier layer

Possible use case for this is the mouse key in vim/tmux environment:
Primary - esc
Secondary - Ctrl (for vim bindings)
double-tap - macro for tmux prefix
tap-and-hold - Alt (for tmux bindings)

I understand this is a non-essential feature, however this would enable power users to use more mojo..

**Comment by mondalaci** [comment]
This may be a fitting request to be implemented in https://github.com/kareltucek/firmware assuming this feature is not already possible with his firmware fork as it's surprisingly powerful. I can't transfer this issue to his repo, but feel free to open it there.

**Comment by kareltucek** [comment]
@mondalaci, could you mark it as exotic feature? It is always nice to be able to list these features... 

@pbartyik What scancode sequences do you expect to be emitted on "double-tap" and "tap-and-hold"? (I mean like `press ctrl, release ctrl`, not actual scancodes.)

**Comment by pbartyik** [comment]
@kareltucek double tap would be possibilities as primary, tap-and-hold would be everything that is currently available as secondary

**Comment by kareltucek** [comment]
> @kareltucek double tap would be possibilities as primary, tap-and-hold would be everything that is currently available as secondary

Well, but what sequence do you actually expect to be emitted? I mean - what do you expect happens with the first tap in the sequence, and how do you want to distinguish between simple primary tap and tap-and-hold?

**Comment by pbartyik** [comment]
> how do you want to distinguish between simple primary tap and tap-and-hold?
Excellent question :) I imagine after tap if there isn't another hit on the same key within X ms it sends the value bound to primary tap. I also imagine this could cause issues with primary tap being possibly delayed
Or am I thinking on the wrong path?

**Comment by kareltucek** [comment]
Both approaches are possible, but you need to know what you want and to be aware of the drawbacks. In the end there will always be either a delay or a bunch of unwanted scancode emits. 

The `ifDoubletap` (and `ifInterrupted`) on the branch simply checks if there was another tap in the past, and if so, then yields to true. I.e., the first tap is send irrespectively of the second one.

The other approach is realized via `ifGesture` or `ifShortcut` or `ifPrimary` or `ifSecondary` - those look into the future and act depending on the future keypresses, but suffer by delays.

The simplest solution (with redundant scancode emits but without delay) might be something like:
```
$ifNotDoubletap holdKey leftControl
$ifNotDoubletap ifNotInterrupted tapKey escape
$ifDoubletap holdKey leftAlt
$ifDoubletap ifNotInterrupted exec <macroname>
```

But in the last scenario (primary action on second tap), it will send all three actions before finally trigering the primary action.

More complicated solution could make use of those "postponing" commands. In that case you should probably use signalling via a register flag to determine whether the instance of the macro is the first tap or the second tap. In pseudocode, it would look like:

```
$ifRegEq 2 1 goTo secondTap
$firstTap:
$setReg 2 1  //this sets register 1 to 1. Registers are basically global variables. 
$ifSecondary final <secondary role>
$ifNotGesture KEYID <primary action>
$delayUntil 200
$setReg 2 0
$break
$secondTap:
$ifSecondary final <the alternate secondary role>
$<the alternate primary action>
```

But honestly, I think you will run into problems with ambiguity of these mappings in the end. But maybe not.

**Comment by Ashod** [comment]
Since double-tap is already supported in the firmware (it toggles layers on/off), I imagine at least for the double-tap functionality it's just a matter of configuring how to interpret it + the UI in Agent.

The power of double-tap as, described in #720, is to leave the primary role of a button to be switching of layers (f.e. the Mouse key, which is extremely handy where it is by default), but when one wants to also occasionally use it as ESC (say, in vim), you just double-tap it, which would act as ESC instead of toggling the Mouse layer On (until clicked again).

I can also use the tap-and-hold described here, for sure (heavy vim+tmux user here), but I'd take a feature that is already supported in the firmware sooner, rather than wait for the whole shebang much later (or never).

I'm also happy to donate some time to making code changes and/or experimenting, if someone can guide me to get started (to flatten the learning curve).

**Comment by mondalaci** [comment]
@Ashod I'm sorry, but I can't justify adding rarely used features such as this one to Agent. Please give a try to [Karel's firmware fork](https://github.com/kareltucek/firmware). Chances are good we'll merge his macro engine to the official UHK firmware eventually.

**Comment by Ashod** [comment]
> @Ashod I'm sorry, but I can't justify adding rarely used features such as this one to Agent. 

@mondalaci: Since I can always fork and implement this myself, I don't mind if you decide not implement it. 

But I must push back on the explanation, because your reason doesn't make any sense (sorry).

Most features in the Agent are by definition rarely used. That's true for almost anything in life (see zipf's law). Things never get equal attention or use. I'm certain macros are used far less than layers, for example (and some keys are used 100s of times more often than others). And surely adding one minor option in the list of things a key can do would neither hurt usability, nor aesthetics or functionality; it's just a question of somebody implementing it.

But, more importantly, neither one of us know that it will not be useful to others. In fact, I suspect it will be used by a certain group of people who have already used up the available options.

Lastly, as I point out, double-tapping is already used, it's just not configurable by users.

> Please give a try to [Karel's firmware fork](https://github.com/kareltucek/firmware). Chances are good we'll merge his macro engine to the official UHK firmware eventually.

Thanks, will do. But doesn't that contract the previous statement? I mean, if the macro engine will possibly be merged, perhaps you meant to say "this feature might be available via the macro engine" ?

I still believe making the double-tapping configurable (i.e. to issue any scan code instead of toggling layers) is a powerful feature that is trivial to add. I just think it's an obvious feature and a trivial one to add too. I can live without it, or just fork and implement it privately, if you don't leave open the possibility of accepting volunteered effort.

**Comment by mondalaci** [comment]
@Ashod Yes, I meant to say "this feature might be available via the macro engine", indeed.

Exposing features via the UI affect a number of parts of the firmware and Agent; they're far from trivial to implement, and far more work than exposing them via Karel's macro mechanism.

> And surely adding one minor option in the list of things a key can do would neither hurt usability ...

I respectfully disagree. If we implemented every single feature ever advised, Agent would be an assortment of numerous knobs, some of which certain people feel very strongly about, but almost no one uses. I'm not perfect and admittedly opinionated when it comes to features. Still, I can also see how frequently various features get requested, and I can tell it's a rare one as opposed to more layers, for example.

**Comment by Ashod** [comment]
@mondalaci Fail enough, thank you.
