### ISSUE TITLE
Left half flickering leds and random keystrokes, then dead while trying firmware update

### ISSUE THREAD

**Issue by vaughnd** [UltimateHackingKeyboard/agent#1346]
Left half of my keyboard started flickering leds and spitting out random keystrokes. I tried a firmware update and now the left side is dead with no leds. Two update logs:

[update.log](https://github.com/UltimateHackingKeyboard/agent/files/5189072/update.log)
[update2.log](https://github.com/UltimateHackingKeyboard/agent/files/5189074/update2.log)

Tried updating on various computers, different cables, with/without bridge cable, disconnecting and reconnecting halves during update, etc. with no joy.

LEDs were doing random nonsenical characters like this before it died:
![2020-09-08 16 53 25](https://user-images.githubusercontent.com/715490/92493188-7fffb480-f1f4-11ea-9080-e5df5bae1bfd.jpg)

Keyboard was ordered on 12 September 2019.

**Comment by mondalaci** [comment]
Based on the symptoms you describe, the root cause of this issue is power related. The firmware upgrade must have also failed because of power issues, and so is the unbricking mechanism.

Has your UHK been working fine up until nowadays? If so, something power related must have changed regarding your setup. Any ideas about what has changed?

Please also retry the update and unbricking on your Macbook while it's battery powered and not connected to mains power.

**Comment by vaughnd** [comment]
Keyboard has been working fine since Oct 2019 on the exact same pc on the same power in the same room. Nothing has changed, and the pc has no other issues. It just started flickering leds and outputting extra random characters while typing out of the blue, with no external cause that I could spot.  My backup Microsoft natural and kinesis keyboards work fine. I tried the firmware updates with laptop on battery, no luck. Why would this keyboard be so sensitive to power issues when no other peripherals get affected?

**Comment by mondalaci** [comment]
Unfortunately, we're unsure about the exact cause of the issue. In any case, we'll replace your UHK. I'll follow up in email.

**Comment by vaughnd** [comment]
That's a pity. I'll wait for your email.
