### ISSUE TITLE
Allow mapping of mouse button 9

### ISSUE THREAD

**Issue by gkleen** [UltimateHackingKeyboard/agent#1537]
Mapping mouse buttons to keyboard keys seems to only be possible for buttons 1 through 8; I would like to map button 9 (which my logitech G703 provides).

**Comment by mondalaci** [comment]
We should figure out how many buttons mice can offer and expose them all via Agent.

MMO mice should give us an idea of how many there are.

**Comment by pmelse** [comment]
the most I'm seeing at time of posting is 20 buttons

**Comment by mondalaci** [comment]
@benedekkupper How many mouse buttons can be exposed via USB? How many do our descriptors allow?

**Comment by benedekkupper** [comment]
> How many mouse buttons can be exposed via USB?

I don't think any OS would reject a mouse interface because it has more buttons than what the OS has bindings for, therefore my answer is 65535. As these buttons are taking up 1 bit USB bandwidth each, the practical limitations apply. The other thing to mention is the physical limitations, a mouse that is supposed to be in the center of the user's palm shouldn't reasonably have all that many buttons on different positions, so I'm already shocked by the 20 buttons mentioned above.

> How many do our descriptors allow?

The firmware has it prepared for extension with `USB_MOUSE_REPORT_DESCRIPTOR_BUTTONS` symbol, which is currently set to 8. I'd still review the code using this to see if it's applied in all areas of the FW, before blindly bumping it up though.

**Comment by mondalaci** [comment]
@benedekkupper Thanks for your insights!

@kareltucek Please review the firmware code according to Benedek's suggestion and look into extending the user configuration. If everything is looking good, let's bump it to 20 buttons. I haven't looked into the related firmware code, and it's possible that the firmware already allows for more buttons and it's only an Agent-side issue.
