### ISSUE TITLE
Touchpad module sensitivity

### ISSUE THREAD

**Issue by giulianob** [UltimateHackingKeyboard/agent#1538]
It appears the touchpad module shows up as a mouse rather than a touchpad to Windows therefore it just gets the same sensitivity as the mouse which for me makes it extremely sensitive. Is it possible to make it less sensitive? Would it be possible to make it show up as a touchpad instead so then perhaps double finger scroll, etc.. could also work?

**Comment by mondalaci** [comment]
Touchpad events are exposed to the host via the USB mouse interface of the UHK, just like for the mouse layer and the other modules. This won't change because we're well on our way to max out the USB endpoints of the microcontroller.

Two-finger scrolling will be provided, and per-module pointer speed will be adjustable, however.

**Comment by mondalaci** [comment]
This is already done by https://github.com/UltimateHackingKeyboard/firmware/issues/351 and the upcoming Agent and firmware releases will expose the wanted settings.
