### ISSUE TITLE
Allow trackball for scrolling on other layers

### ISSUE THREAD

**Issue by SirVer** [UltimateHackingKeyboard/agent#1549]
I just got the trackball module in the mail today and really like its look and feel, great job.

What I found disappointing is the tiny trackbad that is in the keycluster module. That one is very inconsistent and barely works for me. By default it is mapped to scrolling, which makes sense to me.

I tried remapping the trackball module to scrolling as well when the FN layer is active, but unfortunately it does not seem to be possible in the current UHK Agent (Agent version: 1.5.14), is it possible to implement this?

**Comment by mondalaci** [comment]
Hi there, and thank you for the nice words regarding the trackball module.

What do you mean by saying that the mini trackball of the key cluster is very inconsistent and barely works for you? I'm asking because it should be useful for scrolling.

Currently, scrolling is hardcoded according to the [trackball onboarding guide](https://ultimatehackingkeyboard.com/manuals/trackball). We will expose per-layer module navigation modes (such as scrolling) via [smart macros](https://github.com/UltimateHackingKeyboard/firmware/issues/351).

**Comment by SirVer** [comment]
@mondalaci The mini trackball of the key cluster is basically not working for me. If I try very hard to make a consistent movement it sometimes scrolls by half a screen, sometimes by a full screen and sometimes not at all. This is what I mean by inconsistent. Sometimes pressing it strongly helps to make it 'consistent' again for a short amount of time, but then it becomes inconsistent again.

I can feel that it moves, so it does not seem to be physically blocked from movement. Is that expected?

**Comment by mondalaci** [comment]
This is not expected. The resolution of the mini trackball is quite low, but its speed should be consistent. Can you shoot a screencast white moving the mini trackball in all four directions, one by one?

**Comment by SirVer** [comment]
@mondalaci I made a screencast and uploaded it to my google drive. I'd rather not share the link in public since my desk is visible in it. How can I reach you via Email?

**Comment by mondalaci** [comment]
Please shoot an email to support@ultimatehackingkeyboard.com

**Comment by SirVer** [comment]
done.
