### ISSUE TITLE
Access Mod-keys while in "locked" mouse layer?

### ISSUE THREAD

**Issue by TaoK** [UltimateHackingKeyboard/agent#1620]
My apologies if this is not the right place to ask a "how to" question, I have not found any other "community-style" locations for UHK.

I'm learning to use my UHK, and one thing that I find myself doing a lot is navigating (typically but not only web browsing) in the temporarily-locked mouse layer.

In this context, I often need to dismiss (Esc) or confirm (Enter). Enter is easy, Esc is... Awkward: I can map it to "Q" and/or "backtick", but then I'm using esc inconsistently - I want to train myself to use Mod-Q and/or Mod-backtick.

So... I can unmap the left-mod button (accelerated mouse is less important to me, and I can move it to Fn), and with it unmapped I can use Mod-Q or Mod-backtick in locked mouse mode just as I would otherwise (even though the "Mod" is not doing anything) - workaround viable, muscle memory trainable.

However, as soon as I want to do something more interesting, like support "backwards" and "forwards" shortcuts, or Mod-D for Alt-Tab, or anything like that... I run up against a wall. It's not possible to reach the "Mod" layer from the locked mouse layer.

I imagine, given what I read, that something like this *should* be possible with @kareltucek's macros... but I'm simply not intelligent enough to understand how.

Is my problem novel? Is it more easily solvable by something I'm missing?

**Comment by kareltucek** [comment]
So you want to be able to hold mod layer from mouse layer. It is not an entirelly novel problem, but allowing nested layers would make layer navigation harder, and Laszlo prefers not to give people enough rope to hang themselves...

With my fork, it should suffice to map a `$holdLayer mod` macro in your mouse layer. (I.e., macro containing a text action with that text.)

**Comment by TaoK** [comment]
Wow, that certainly sounds simple!

I just tried (flashed the "uhk-fw-8.10.10.kt.3" firmware, added a macro called "HoldModLayer", with one text action with the text "$holdLayer mod", and mapped the "Mod" key to that macro in the mouse layer), and unfortunately nothing happened. The key turns purple in the mouse layer, presumably to tell me it's mapped to a macro, but pressing it and a mod-layer key doesn't do anything (regardless of whether mouse is "locked" or manually held).

I thought "maybe he meant 'Mod', not 'mod'...", and tried changing the macro text to "$holdLayer Mod": that did *something*, but not what I expected - it took me (while held) to the mouse layer of the "COM" (Colemak for Mac) Keymap! Reviewing the doc I see that was never going to work ("mod" was correct), but I'm still confused about why it did *something* where the correct form did not...

Is the fact that I'm on a v2 UHK relevant?

**Comment by mondalaci** [comment]
@kareltucek I'm not against merging more advanced features, such as this, eventually, but first, the smart macros PR should be merged. Wink, wink :)

**Comment by kareltucek** [comment]
> and unfortunately nothing happened.

I see. I am creating a ticket for it, but I am afraid it will have to wait -> https://github.com/kareltucek/firmware/issues/71 .

A workaround is be to replace the native layer switchers with corresponding macros (`$toggleLayer ...`, `$unToggleLayer ...` and `$holdLayer ...`) and stop using the legacy layer switching, but I see that it is rather an overkill for your usecase. 

(On the context - the macro layer switching mechanism is separate from the legacy one. There is some mechanism which defines interoperability rules between the two mechanisms, but I do not recall the intended logic behind it. But apparently, the interoperability is currently defined so that legacy layer switching works on top of macro layer stack, but not the other way around. I am afraid that the conclusion will be that current behaviour is by definition "correct", and that "fixing" it will require some rather fundamental changes to the logic. I guess I will introduce a switch which will force all layer switching to be handled by just the one or the other mechanism.)

**Comment by TaoK** [comment]
> A workaround is to replace the native layer switchers with corresponding macros ($toggleLayer ..., $unToggleLayer ... and $holdLayer ...) and stop using the legacy layer switching, but I see that it is rather an overkill for your usecase.

May be overkill, but I'm a bit obsessed!

I just tried, and it *almost* works, but not quite:
* I have a simple "ModLayer" ($holdLayer mod) macro, and have it mapped to the Mod key in base and mouse layer
* I have a simple "FnLayer ($holdLayer fn) macro, and have it mapped to Fn keys in base layer
* I have a reasonably-simple "MouseLayer" ("$holdLayer mouse" + "$ifDoubletap toggleLayer mouse"), mapped to the mouse key in base layer
* I have a simple "LayerOff" ($unToggleLayer) macro, and have it mapped to the mouse key in mouse layer.

My keyboard is suddenly quite purple because of the macroed mod keys, and everything works *except* turning off the mouse layer once locked/toggled - it looks like the untoggle just doesn't work :(

I can work around this for my simple purposes by using "$toggleLayer base" instead, but I'm a bit worried that I'm filling up some stack that will overflow eventually :)

Am I missing something?

**Comment by kareltucek** [comment]
I see. This certainly is a bug -> https://github.com/kareltucek/firmware/issues/73. 

The reason is that it is missing a base layer on the stack which is improperly initialized.

> I can work around this for my simple purposes by using "$toggleLayer base" instead, but I'm a bit worried that I'm filling up some stack that will overflow eventually :)

It should be safe. In that case, bottom record will get discarded.

I will deal with this one soon, however, releasing a new firmware is somewhat compicated at the moment due to lack of compatible agent release, so please stick with the workaround for the time being.

**Comment by TaoK** [comment]
Thank you so much, this is awesome!!

**Comment by mondalaci** [comment]
I'm closing this issue. Feel free to continue this discussion in https://github.com/kareltucek/firmware/issues/73
