### ISSUE TITLE
Keyboard Password Protection

### ISSUE THREAD

**Issue by dornhe** [UltimateHackingKeyboard/agent#1644]
When password protection is activated, one first types the correct sequence of keys, before any signal is send from the keyboard to the connected device.

**Comment by mondalaci** [comment]
Am I right that you're suggesting that after connecting the UHK via USB, the correct password should be entered before the UHK sends anything to the host?

If so, what would be the practical advantage of this feature?

**Comment by dornhe** [comment]
It has advantage, when you want to store information on your keyboard, e.g. your address, telephonenumber, ... In this case you would not want somebody else to plug your keyboard into their own device and simply download this information.

**Comment by mondalaci** [comment]
I understand your use case, but are you aware that your UHK configuration is stored unencrypted in its on-board memory? Anyone gaining physical access to your UHK can retrieve this information.

**Comment by dornhe** [comment]
Yes. This is clear. A password on the keyboard only offers superficial protection. But on a day-to-day basis this could be enough. After all, your credit card information is stored in plain text in your wallet.

**Comment by kareltucek** [comment]
If I understand what you are after, you can do it with https://github.com/kareltucek/firmware . 

Use a macro like `$ifGesture transitive 10 79 80 80 73 9 75 81 switchKeymap QWR` (figure out the keyids using another macro - `$resolveNextKeyId`), bind it on the first letter of your password in an otherwise empty keymap, and make the keymap default.

To be clear - it will still be possible to read the configuration via Agent even without the password. That is, attacker will need physical acces to your UHK, but will *not* need to disassemble it.

> After all, your credit card information is stored in plain text in your wallet.

Well, you don't leave your wallet on office desk over weekends, do you?

**Comment by dornhe** [comment]
>Reading it again, I guess you meant that not even USB interfaces should be activated until correct password is entered?
Correct. But I am not a hardware guy, so I would not know the specifics. Another thought are file permissions as you would find them in an OS. 
> Well, you don't leave your wallet on office desk over weekends, do you?
Yes. Usually. Yet I might forget.

**Comment by dornhe** [comment]
> I'm sorry, but we haven't received any demand for this feature other than this issue, so we can't justify the development resources.
> 
> I'm closing this issue, but anyone who visits it, feel free to upvote it via the first comment.

This is rational. Thank you.
