### ISSUE TITLE
Scancode as Secondary Role

### ISSUE THREAD

**Issue by rafaelpirolla** [UltimateHackingKeyboard/agent#1645]
I would like to use a normal scancode as secondary role (e.g. holding "s" should produce "-").

**Comment by kareltucek** [comment]
Do you really mean secondary role (i.e., a role which will activate on interaction with another key) or do you simply mean that long press should produce different action?

In both cases, you may experiment with https://github.com/kareltucek/firmware . The latter case is described in https://github.com/kareltucek/firmware/issues/70 .

**Comment by rafaelpirolla** [comment]
You are right @kareltucek, I meant long pres- produce different action. But I think this falls into the issue of the home row mod that there's no way to find a good value for milisecs not to create typos.

Thanks for pointing the solution.

**Comment by kareltucek** [comment]
I guess its consequence of the delay. You can fix it by prefixing all commands of the macro with `postponeKeys`. 

I am not sure what the outcome will be if multiple such keys get pressed in quick succesion. Either way, feel free to create a new issue in the linked repository and continue the discussion there. I think this problem is worth further pursuit.

**Comment by kareltucek** [comment]
> But I think this falls into the issue of the home row mod that there's no way to find a good value for milisecs not to create typos.

Actually, I think it is not exactly the same problem class. "Longpress" directly implies expected resolution strategy, as well as it poses a clear requirement on your typing style (that you should release keys immediately). If it does not work for a person, the problem is clearly his typing style, not the feature itself.

The general home row mod feature is different - there are multiple strategies to deal with it, each working with different typing style. My typing style is incompatible with "longpress" strategy, which led me (maybe incorrectly) to primarily focus on different strategies.

**Comment by rafaelpirolla** [comment]
postponeKeys solved the issue to my typing style it seems. Your firmware rocks @kareltucek :)
