### ISSUE TITLE
Add new keymap page initialization is slow

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#186]
When I click on the + icon to invoke the add new keymap page I have to wait almost for a second for it to appear with my Core i7-4770K.

When I click on the individual keymaps in the side menu the time it takes to load one keymap is about 0.3s which is tolerable, although noticable. I assume that the 3 keymaps of the add new keymap page take 3*0.3s.

If the above assumption is correct, this will become very slow very quickly. We should either optimize the rendering of the keyboard, and/or lazily instantiate the keyboards of the add new keymap page as the user scrolls.

**Comment by NejcZdovc** [comment]
Yes you are correct. Because we are serving keymap slider, we are rendering in the current example 9 layers.

Little test:
3 keymaps -> 9 layers -> 1.25s
15 keymaps -> 45 layers -> 4.70s

@fjozsef As you can see from the image the main problem is scripting. I am not really familiar with svg keyboard rendering code, do you have any suggestions for improvements?

One thing that I did is changed `changeDetection `property I see a little bit of improvement for the main components in this rendering flow. I didn't change this for all components in it.

![image](https://cloud.githubusercontent.com/assets/9574457/20513320/6b6b9d18-b085-11e6-9bda-2db93facb18e.png)

**Comment by mondalaci** [comment]
Deprecated by #459.
