### ISSUE TITLE
FR: automatic configuration export on modification/save

### ISSUE THREAD

**Issue by laur89** [UltimateHackingKeyboard/agent#1935]
Similar to how something like [Aegis](https://github.com/beemdevelopment/Aegis) does it, it'd be nice if one could configure agent to save a configuration export to a pre-determined location on each `save` action, so we always have a backed-up copy of it available.

**Comment by mondalaci** [comment]
Agent is already working this way. Please see its configuration page. There's a related filesystem directory.

**Comment by laur89** [comment]
Sorry I can't seem to find which `configuration page` you're referring to.

In `~/.config/uhk-agent/` directory, there is a file called `2317900877.json` that appears to contain configuration. Is this the one to back up? Does the filename change? Can't quite figure what the filename refers to -- doesn't look like a timestamp.

**Comment by ert78gb** [comment]
The `~/.config/uhk-agent/<device-id>.json` contains the user-configuration that Agent saves before update the user configuration on the keyboard. The reason is if any error occurs why saving the config and the config will be corrupt on the keyboard we could restore you latest modification from this file.

The `<device-id>` is the unique identifier of you UHK device. If you have multiple device we could track the modification/keyboard.

The `~/.config/uhk-agent/user-configs/` folder contains the successfully saved user configurations in binary format independently from the device.
We use the binary format to save disk space.
The file name structure is `{timestamp}-{md5-hash}.bin`. The `timestamp` in `YYYYMMDD-HHmmss` format. The `md5-hash` is the md5 hash of the user configuration.
The `~/.config/uhk-agent/user-configs/` contains the archives of all of your device, so if you have multiple device you could easy apply the archived user config to multiple device on the user configuration page.

**Comment by laur89** [comment]
Thanks for the explanation. Is there any benefit (or downside for that matter) in backing up the `<device-id>.json` file in addition to the user-configs/ dir?

**Comment by ert78gb** [comment]
I think it has benefit
- the `<device-id>.json` contains the before save state. The `~/.config/uhk-agent/user-configs` contains the after save version.
- if someone uses more UHK then they have device specific backup. If they use multiple computer they have to check the timestamp of `<device-id>.json` file to find the latest version.

After Agent successfully saved the user config to the keyboard we could delete the `<device-id>.json` file because the history contains this config. I think we never thought about the deletion of `<device-id>.json` file.
We could delete it but:
-  it would be a breaking changes because maybe someone build a workflow in the existence of this file
- we have to modify Agent. If the user config corrupt in the keyboard then first have to check the `<device-id>.json` if it does not exist try to find the first compatible user configuration from the history. I think the current logic/implementation is more simple.

Overall I think keep the `<device-id>.json` has more benefit then drawback
