### ISSUE TITLE
[Feature Request] Trackball Acceleration Threshold Adjustment

### ISSUE THREAD

**Issue by M-Kerr** [UltimateHackingKeyboard/agent#2000]
It would be helpful to customize the threshold that determines how much px/s input is considered "low-speed" and "high-speed."

To my feel, the trackball transitions to "high-speed" acceleration at too low of an input px/s.

Where is this threshold determined in the codebase?

**Comment by kareltucek** [comment]
See https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md . Since shape of the curve is determined by a fixed exponent, it should suffice to increase `speed` in order to get a shape equivalent to higher mid speed.

But if you prefer to adjust the value directly in the code, it is this line: https://github.com/UltimateHackingKeyboard/firmware/blob/23b1e9f357d56efdbd2bf2b8f446105cab941939/right/src/mouse_controller.c#L270

**Comment by M-Kerr** [comment]
Thank you, Karel!On Apr 8, 2023, at 06:57, Karel Tuček ***@***.***> wrote:﻿
See https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md . Since shape of the curve is determined by a fixed exponent, it should suffice to increase speed in order to get a shape equivalent to higher mid speed.
But if you prefer to adjust the value directly in the code, it is this line: https://github.com/UltimateHackingKeyboard/firmware/blob/23b1e9f357d56efdbd2bf2b8f446105cab941939/right/src/mouse_controller.c#L270
