### ISSUE TITLE
Can't use UHK Agent

### ISSUE THREAD

**Issue by smalake** [UltimateHackingKeyboard/agent#2009]
I installed UHK Agent to my Mac.
But, error is occured that "Please power cycle your keyboard invalid hardware configuration: index out of bounds".
I keep getting the same error no matter how many times I reconnect.
How can I use UHK Agent?

MacOS version: Ventura13.3.1
CPU: Apple silicon M1pro
UHK Agent version: 2.1.2

![スクリーンショット 2023-05-01 17 36 12](https://user-images.githubusercontent.com/41889150/235707865-1a72c08e-9c96-46fa-b3f9-112717eed641.png)

**Comment by mondalaci** [comment]
@ert78gb Please help with this issue.

**Comment by ert78gb** [comment]
This error occurs when we can't parse the hardware configuration of the keyboard.

@smalake pls run the `/Applications/UHK\ Agent.app/Contents/MacOS/UHK\ Agent -- --log=all > agent.log` command in terminal and send the log file to me in private email. If it does not contain any sensitive information you can share here too. 
my email is `ert78gb at gmail.com`

**Comment by smalake** [comment]
Igot log, and I have attached the log.
I got it multiple times and it's the same content each time.
Thank you for your response.

[agent.log](https://github.com/UltimateHackingKeyboard/agent/files/11378732/agent.log)

**Comment by ert78gb** [comment]
The log file is almost empty. If you run the `/Applications/UHK\ Agent.app/Contents/MacOS/UHK\ Agent -- --log=all` then do you see anything else in the terminal?

**Comment by smalake** [comment]
Sorry, I made a mistake how to get log yesterday.
I got the log again, so please check it.

I attached the acquired log to the email, so please check it.

**Comment by ert78gb** [comment]
@smalake The hardware configuration of the keyboard is corrupt. We don't know how is it possible. 
My question is could you clone the agent repository and build agent from the source code?
A https://github.com/UltimateHackingKeyboard/agent/blob/master/README.md contains the documentation.

After the building 
- switch to the usb directory `cd packages/usb`
- write the new hardware configuration to the keyboard `./write-hardware-config.ts` the script expect 2 argument. 
  - the first argument is `uhk60v2` because your keyboard is a second generation based on the logs.
  - the second argument is `iso` or `ansi`. It depend from your keyboard layout.

So the command will `./write-hardware-config.ts uhk60v2 ansi` or `./write-hardware-config.ts uhk60v2 iso`

If you can't run the script then we will figure out other method

**Comment by smalake** [comment]
I tried the method you suggested and it worked fine.
Thank you very much!
