### ISSUE TITLE
Don't leave a hole in the macro array when deleting a macro

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#211]
The macro array must not contain any holes. If the macro array contains elements 0, 1, and 2 and the user deletes macro 1 we end up with a hole in the array. When deleting a macro other than the last one, the last macro element should be moved to the place of the deleted element.

**Comment by fjozsef** [comment]
It is not clear for me which array will have "holes" (=undefined?) elements. Neither in the macro state nor in any representation we store array with holes.
Of course the macro ids possibly not sequentical, but I think that is the reason why they exists, otherwise we could remove it and use array index instead.

Note: In the url we are using ids.

**Comment by fjozsef** [comment]
Related to #212
