### ISSUE TITLE
Feature Request: Variables in Macros

### ISSUE THREAD

**Issue by seanparkross** [UltimateHackingKeyboard/agent#2174]
Would be great to have access to a few key variables in Macros... eg: today's date.

**Comment by seanparkross** [comment]
A stretch goal would also be basic scripting in Macros 🤤

**Comment by kareltucek** [comment]
You have noticed the command macro action, its "smart macro" documentation in the right pane, and a link at its end that leads to yet another documentation that contains an additional bunch of more advanced commands, right? Because UHK does support what I would call basic scripting as well as variables.

As to todays date, UHK does not know todays date, so wanting it to print it is futile. (You want an editor with a snippet engine for that, like vim with ultisnips. Keyboard cant do that job very well as it does not have acces to the text buffer and so does not know a lot of context information.)

**Comment by mondalaci** [comment]
I think, given the capabilities of the hardware, this is a non-issue, so I'm closing this one. Feel free to follow up, nevertheless.
