### ISSUE TITLE
Unable to flash latest firmware

### ISSUE THREAD

**Issue by saltwick** [UltimateHackingKeyboard/agent#2175]
I have been trying to configure my UHKv2 using the Agent software, but I have been unable to get it to work. First, the Agent software is unresponsive and constantly crashes. When I am able to get to the firmware update screen, it is unable to complete the firmware update. I've attached my log file with the errors.

Windows 11 23H2
Agent 3.22
Attempting to update firmware to 10.5.0

[uhk-agent.log](https://github.com/UltimateHackingKeyboard/agent/files/14380641/uhk-agent.log)

Thanks!

**Comment by ert78gb** [comment]
Hi @saltwick,

The reason of the Agent unresponsiveness and the firmware upgrade crashes because the USB communication is very slow. Every USB read takes 10 seconds.

Earlier other users experienced it when they 
- connected special USB device (microphone) to the computer, which response time is slow
- used keyboard capture software
- used USB hub

Please try to use Agent by paying attention to the above mentioned.

**Comment by saltwick** [comment]
This fixed it! I had an Elgato Wave microphone plugged in. Is this guidance posted somewhere that I missed? Thanks!

**Comment by mondalaci** [comment]
Great job finding the cause of the issue!

We've never encountered this issue, which is why it's not featured anywhere. Chances are this issue was caused by a combination of your USB hub / docking station / KVM switch and the microphone.
