### ISSUE TITLE
Module page changes

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#2217]
![image](https://github.com/UltimateHackingKeyboard/agent/assets/300402/913c3777-7ffa-40ad-a90d-a6154bee1aa1)

- On every module page rename the Miscellaneous header to "Scrolling direction".
- Merge the "Invert horizontal scrolling" and "Swap axes" options into the "Scrolling direction" section.
- Thus, the new order of the items in the "Scrolling direction" section is: "Invert vertical scrolling", "Invert horizontal scrolling", and "Swap axes"
- Display the "Invert horizontal scrolling" option on every module page, but only display the "Swap axes" for the key cluster.
- Remove the "Key cluster settings" option because it's empty.
- On the touchpad page rename "Touchpad settings" to "Extended settings".

**Comment by ert78gb** [comment]
> Display the "Invert horizontal scrolling" option on every module page, but only display the "Swap axes" for the key cluster.

The `Invert horizontal scrolling` property currently [parsed](https://github.com/UltimateHackingKeyboard/firmware/blob/b0ed6b8d039362905f22b4ba7d2107d3ce28a6ca/right/src/config_parser/parse_module_config.c#L81) as key cluster property.I think we  also have to modify the firmware to handle every module this property.

`keyClusterInvertHorizontalScrolling` is the property name in the serialised user configuration. I think we have to rename it too.
I can't decide it is major user config change or not.

@mondalaci @kareltucek what is your opinions

**Comment by kareltucek** [comment]
> The Invert horizontal scrolling property currently [parsed](https://github.com/UltimateHackingKeyboard/firmware/blob/b0ed6b8d039362905f22b4ba7d2107d3ce28a6ca/right/src/config_parser/parse_module_config.c#L81) as key cluster property.I think we also have to modify the firmware to handle every module this property.

Oops. Yes.

> I can't decide it is major user config change or not.

I would list is as minor, although technically, removing `keyClusterInvertHorizontalScrolling` from the config should be major as ti voids backward compatibility.

**Comment by ert78gb** [comment]
User imports a user config with `keyClusterInvertHorizontalScrolling` and not change anything just export it and the`keyClusterInvertHorizontalScrolling` will renamed to `invertHorizontalScrolling`.

The same thing will happen in firmware side. After the user config parse read the `SerializedModuleProperty_Keycluster_InvertScrollDirectionX = 255` and save as `SerializedModuleProperty_InvertScrollDirectionY = 10` we can't keep the 255 for every module because it is already used as `SerializedModuleProperty_Touchpad_HoldContinuationTimeout = 255,`

We can easily handle this change in code but I don't know how logical is. I think we have to keep the `SerializedModuleProperty_Keycluster_InvertScrollDirectionX = 255` property as reserved property to prevent reuse.

Maybe I over worry the things but I just would like to prevent some future conflicts

**Comment by kareltucek** [comment]
> I think we have to keep the SerializedModuleProperty_Keycluster_InvertScrollDirectionX = 255 property as reserved property to prevent reuse.

Yes, let's keep it reserved.

**Comment by mondalaci** [comment]
> Yes, let's keep it reserved.

I agree. We can reuse the reserved property in a future major configuration change.

**Comment by mondalaci** [comment]
Use [uhk-firmware-11.0.2-f9f87630.tar.gz](https://github.com/UltimateHackingKeyboard/agent/files/14966935/uhk-firmware-11.0.2-f9f87630.tar.gz) containing https://github.com/UltimateHackingKeyboard/firmware/pull/768

**Comment by mondalaci** [comment]
[uhk-firmware-11.0.2-f9f87630.tar.gz](https://github.com/UltimateHackingKeyboard/agent/files/14967130/uhk-firmware-11.0.2-f9f87630.tar.gz) - Now the user config version is bumped to 7.1.0
