### ISSUE TITLE
Media key missing scancodes

### ISSUE THREAD

**Issue by fjozsef** [UltimateHackingKeyboard/agent#225]
The following scancodes are missing and assigning them to a key is not possible.

- Next track
- Previous track
- Stop
- Play/Pause
- Eject

**Comment by mondalaci** [comment]
http://www.usb.org/developers/hidpage/Hut1_12v2.pdf - The Consumer page starts from page 75

**Comment by mondalaci** [comment]
I'm ready with the firmware side of this. It was considerably more complex than I imagined, so some explanation follows.

Previously, the UHK only exposed 1 USB interface for sending scancodes. Now it exposes 3 which are the following:

1. Basic keyboard: Generic Desktop page (0x01), Keyboard usage usage id (0x06)
2. Media keyboard: Consumer page (0x0c), Consumer Control usage id (0x01)
3. System keyboard: Generic Desktop Page (0x01), System control usage id (0x80)

The basic keyboard interface sends regular scancodes that are listed in Table 12, starting from page 53 of the above HUT document.

The media keyboard interface sends media scancodes that are listed in Table 17, starting from page 75 of the document. Unlike the rest of the scancodes, these are 16 bit codes. It's important to note that I [explicitly deleted](https://github.com/UltimateHackingKeyboard/firmware/commit/117332bb67689fc55d13131fdbe1da2395e60c8b#diff-63f01fd4ef699b36cd0edcb1180fe877) the media scancodes of the basic keyboard interface because as it turns out, they only work on Linux. We must use the media keyboard interface for this purpose.

The system keyboard interface sends system scancodes that are listed in Table 6, on page 27, starting from the 0x80 value. According to my research, only the Sleep and Power Down codes work are respected by OSes. Again, it's important to note that even though some system scancodes like Sleep can be found on the consumer page, they only work on Linux, so the system keyboard interface must be used for this purpose.

It'd make sense to allocate 2 bits within the key action type byte of the keystroke action to select one of the following:

1. basic scancode
2. short 8-bit media scancode
3. long 16-bit media scancode
4. system scancode

The fields of the keystroke action should be the same in all these 4 cases. Regarding the serialization, the only difference is that the long 16-bit media scancode is 16-bit wide unlike the rest which are 8-bit wide.

**Comment by fjozsef** [comment]
@mondalaci #294 has been merged. What do you think? Can we close this in favor of #303 ?

**Comment by mondalaci** [comment]
@fjozsef Yes, totally. Good point! Just closing it.
