### ISSUE TITLE
Typing behaviour :: "Double tap to lock layer timeout" and "Double tap timeout" should have different tooltips

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#2261]
Agent 4.1.0
Device -> Typing behaviour

![image](https://github.com/UltimateHackingKeyboard/agent/assets/591785/98c4c9b0-28d8-46bd-9586-947a406f4cc8)

Tooltip is the same for two different settings.

I think it should explain the difference between these settings, so the two tooltips should be different.

**Comment by mondalaci** [comment]
@mhantsch Thanks for the heads-up!

@kareltucek Which one should we change and how?

**Comment by kareltucek** [comment]
Clearly the second one. Since you insist on not mentioning the `ifDoubletap` condition, then probably just `Double tap to lock layer timeout configures doubletap timeout.`. Which however does not add any new information, so the tooltip can be left out altogether.

(Also, I told you. Twice actually.)

![2024-05-07-081458_857x147_scrot](https://github.com/UltimateHackingKeyboard/agent/assets/3447497/10b597e1-5564-4f98-9cd1-adc76e78b1d4)
---
![2024-05-07-081515_887x147_scrot](https://github.com/UltimateHackingKeyboard/agent/assets/3447497/133883a4-b933-4aba-a22e-f46cccafcea8)

**Comment by mondalaci** [comment]
@kareltucek Sorry for the oversight. I have to deal with a lot nowadays.

@ert78gb Please change the second tooltip according to the one suggested in the forum.
