### ISSUE TITLE
Rhythmic freezing of Agent 

### ISSUE THREAD

**Issue by Tanz0rz** [UltimateHackingKeyboard/agent#2336]
Agent is constantly locking up in a perfect rhythm.

OS: Windows 10
Version 4.2.0

Behavior:
- Unfrozen for a half second
- Frozen for one second
- This repeats permanently  

No other part of my system is effected while the software is open. Reboots of the application and computer do not help. This happens with my UHK 2.0 connected and disconnected.

**Comment by mondalaci** [comment]
Please try to reproduce this issue with another computer. This is hardly an Agent issue because no one else reported it, and the latest Agent version has been released for a while.

**Comment by ert78gb** [comment]
Based on the symptom there is a slow USB devices connected to the computer. Other case in #1482.
Could check a slow device cause the freeze?

**Comment by Tanz0rz** [comment]
> Please try to reproduce this issue with another computer. This is hardly an Agent issue because no one else reported it, and the latest Agent version has been released for a while.

The issue is happening exclusively with the Agent software on my Windows computer with or *without* the keyboard connected. Agent has been reinstalled, computer rebooted, etc. 

> Based on the symptom there is a slow USB devices connected to the computer. Other case in https://github.com/UltimateHackingKeyboard/agent/issues/1482.
Could check a slow device cause the freeze?

I think you are right. If I open Agent from the command line, you can see that the freezing is almost perfectly in line with the USB polling interval from Agent (video attached). 

https://github.com/user-attachments/assets/65d3181a-0185-4a09-92b5-5f5e3ea3e31a

**Comment by ert78gb** [comment]
> Add a command line flag that triggers Agent to poll for USB devices exactly one time on startup and disables the persistent looping polling. That should be extremely simple and would work for people who have gone deep enough to find this issue on GitHub.

The polling not just simple poll to detect the keyboard is connected or not. The polling reads status information that affect the Agent UI.

**Comment by Tanz0rz** [comment]
> > Add a command line flag that triggers Agent to poll for USB devices exactly one time on startup and disables the persistent looping polling. That should be extremely simple and would work for people who have gone deep enough to find this issue on GitHub.
> 
> The polling not just simple poll to detect the keyboard is connected or not. The polling reads status information that affect the Agent UI.

When Agent first starts, it can cache the USB device ID for the keyboard, right? It seems like the problem is due to Agent asking for information about every USB device on my computer every second after it has already found and connected to the keyboard.

**Comment by ert78gb** [comment]
Agent queries the USB devices list. This list contains USB descriptors that queried by the OS. Even if we cache the USB device ID (device path) the user can connect an other UHK keyboard any time. Agent should detect it and ask the user to remove one device otherwise it could cause problem under the firmware upgrade process.

I am sure we could improve Agent internal processes but the question is it worth the effort.

**Comment by Tanz0rz** [comment]
> Agent queries the USB devices list. This list contains USB descriptors that queried by the OS. Even if we cache the USB device ID (device path) the user can connect an other UHK keyboard any time. Agent should detect it and ask the user to remove one device otherwise it could cause problem under the firmware upgrade process.
> 
> I am sure we could improve Agent internal processes but the question is it worth the effort.

How much work would it be for you to add a CLI flag that does the USB device list query a single time on startup? I have 8 USB devices connected to the back of my computer and they are not easy to access (or keep organized).

**Comment by Tanz0rz** [comment]
Can I get a little more empathy from you here? I just paid $500 for a brand new cutting edge keyboard. The software critical to its function/customization is unusable for me in its current state. The workarounds for me at the moment are to temporarily unplug 8 devices from the back of my computer every time I want to update the keyboard layout or build a new computer.

**Comment by ert78gb** [comment]
Sorry for the late response. We fully understand your frustration and sorry for the inconvenience. 
Even if we don't answer immediately it does not mean we don't thinking or working on the problem. We response when we know exactly what answer to our customers. We don't prefer the fast and meaning less responses like "Our engineers are working on the problem ..."

I created the #2337 PR that maybe fixes the UI freeze. I am writing maybe because I don't have any special USB device that has slow response time.
Only contributors can download the artifacts of the PRs. It is a GitHub limitation so I uploaded the windows relevant files to a Google Drive folder. 
- x64: https://drive.google.com/file/d/1KN_i5MbQ8M7O1CSY03ybq1CObE3Ci5F3/view?usp=sharing
- I32: https://drive.google.com/file/d/1p3C4v38usRs1sRCcc_g0RQT1zbFuIVyr/view?usp=sharing

Please test.

If it does not solve the problem please provide the exact OS number. Agent writes this information to the console and the log file when starts. Please also provide the product name or website link of the USB device that cause the freezing. I would be happy if you provide this information even the problem solved for the future. I know find the device is time consuming, but next time enough just unplug 1 device instead of 8.

**Comment by Tanz0rz** [comment]
Just tested it and this has fixed the issue for me.

To your last request of finding the slow USB device, I did meticulously test all the devices when I was originally debugging the problem. The issue was not caused by any specific device. It was caused by having 2 or more other USB devices plugged in. I tested 0 devices, then 1, then 2 and noticed increasing lag with each additional device. I repeated this test with 2 other USB devices and had the same results. So this makes me think the problem is with the USB hardware on my motherboard (GigabyteB650 Aorus Elite AX).

Thank you for helping with this!

**Comment by ert78gb** [comment]
Thanks for your feedback. 
Your motherboard not old. I don't know what cause the problem. The fact is windows has the lowest IO performace of the OSs that I use.
Please use the provided Agent version until we officially not release the new version
