### ISSUE TITLE
UHK detection screen

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#258]
Agent-electron should start up by searching for the UHK. This should involve calling `usb.findByIds()`. Only the following should be displayed in center of the window:

![searching-for-uhk](https://cloud.githubusercontent.com/assets/300402/22854890/c4b44812-f076-11e6-97b9-4b0d05fbde5e.png)

If `usb.findByIds()` returns `undefined`, the following should be displayed:

![agent-cannot-find-uhk](https://cloud.githubusercontent.com/assets/300402/22854742/611168a4-f075-11e6-8406-b72da69b9622.png)

and then `usb.findByIds()` should be polled on a 100 ms basis as long as it returns with a non-undefined value, at which point Agent should proceed further.

During the execution of Agent, if the UHK gets unplugged it should be detected and we should reveal the "Cannot find your UHK" screen again.

**Comment by fjozsef** [comment]
@mondalaci Why the two screen? I would skip the first since the uhk can be detected at bootstrap and based on that we can navigate the user to the main screen or to the 'Cannot find your UHK screen'.
The searching / detection is in progress in both cases, so it seems redundant to me.
Moreover I assume `usb.findByIds()` is quick (since it syncronous) so the `Searching for your UHK` would be present only for a very short time.

**Comment by mondalaci** [comment]
@fjozsef You've just made me conscious about `usb.findByIds()` being a synchronous, split-second call, so I agree that displaying the "Searching for your UHK" screen makes no damn sense. :) Feel free to ignore it.

Great catch!
