### ISSUE TITLE
Key title layouts

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#27]
Prepare layouts for the keys with different informations displayed:

- keypress
- keypress with modifiers
- keypress with long press actions

These svg files should go into an examples folder.

**Comment by csanyiarpad** [comment]
Take a look at the svg committed above. As the commit messaged says it contains good and bad examples as well. Below I list my opinions about the different representation:

Bad examples:
* key "!1": the text is too small on it (I have just resized the original one to fit in)
* key "@2": the icons are character entities, which causes that they could get different dimensions on different platforms. So we will convert them to path.
* key "Q", "W", "E": the blue highlight is not a good decision as it will disappear once the popover is open (as the whole key would have a blue background). Also the not active modifiers are called out too much by the white color.
* key "X": the grey modifier text is not readable enough on the highlighted keys
* general: when not using icons, try avoiding the letter sequence "S", "C", "A", "M". 

Good examples:
* keys "G", "H", "J", "Z", "C", "V", "B", ...: shows the different states of the key and it's modifiers.
* the icons look great on key "@2", I'll prepare for the other platforms as well.

I just realized that I left two magenta colored helper squares on the image.

**Comment by mondalaci** [comment]
I agree about the good and bad examples, and this looks like a great first version. Please let's iterate further based on what we discussed recently. Let's remove the bad examples and add all 3 platform-specific versions. Let's also add examples for mouse actions, switch keymap actions, and play macro actions if time permits.

As for the "@2" key, we can't covert such texts to paths. The reason is that we want to be able to display a wide variety of text according to key actions and we can't pregenerate the path representation of every possible combinaton. We'll have to make sure to get the dimension of the text right real time. JavaScript for the rescue.

Given that the example SVG will be modified, and eventually deleted from the repo let's always reference the actual version. The current one is https://github.com/UltimateHackingKeyboard/agent/blob/891d29ab2dfe0e52dccd69b6dd24190af112db58/examples/uhk.key-design.svg

**Comment by mondalaci** [comment]
Please let me write a quick todo summary:

* Remove highlighted key colors and make every key feature the same gray background. There is no need to highlight keys in the future thanks to the visual SVG diff feature of GitHub.
* Remove every separator line to minimize visual noise.
* Don't feature modifier flags when there's a long press action present, since they're mutually exclusive.
* Don't feature modifier flags when none is set.

The above will clean up the current design. Going forward, let's mockup the switch layer action, mouse action, play macro action, and switch keymap action.

Please let's try to focus on the big picture first, and mockup every action. Then we can discuss the nuances of the layout.

Thank you!

**Comment by csanyiarpad** [comment]
For the menu icon there wasn't really a good match in Icomoon, so I started from the basic one, which you can find on most of the keyboards (therefore it will be easy to recognize).

**Comment by mondalaci** [comment]
Is this supposed to be closed, @csanyiarpad?

**Comment by csanyiarpad** [comment]
I'm adding the missing icons, and will close this.

**Comment by csanyiarpad** [comment]
All the functions have a key design, and the necessary icons has been added.
