### ISSUE TITLE
Add system scancodes

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#304]
Please create a new "System" category at the end of the scancode selector of the key action popover and add the following *system* scancodes in it:
* Power down: 0x81
* Sleep: 0x82
* Wake up: 0x83

**Comment by attilacsanyi** [comment]
Is it ok to store those new _system_ scancodes in decimal as others? so
`0x81 = 129, 0x82 = 130, 0x83 = 131` ? @mondalaci

**Comment by fjozsef** [comment]
@attilacsanyi It must be. You can't store hexadecimal numbers in JSON.

**Comment by attilacsanyi** [comment]
Do we have any icons for those system keys? @mondalaci @fjozsef
`Power down` and `Wake up` cannot fit into one key. If we use **Power**, **Sleep** or **Wake** abbreviations then they can fit.

Also due to special logic in `findScancodeOptionByScancode` _(keypress-tab.component.ts)_, we have to define those 3 new system keys before `media` keys in `scancode.json` otherwise, different media keys going to be loaded due to `id === scancode` condition after remap.

**Comment by fjozsef** [comment]
**Sleep**: images/icons/kbd__fn--sleep.svg, just need to be registered,
I can't find an icon for the other two.

**Comment by attilacsanyi** [comment]
Thank you guys, icons were added.
Let me know if I have to use a different one from the [icomoon](https://icomoon.io/#preview-ultimate) pack.
