### ISSUE TITLE
Enforce further keymap abbreviation rules

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#341]
1. Currently, it's possible to type any character into the abbreviation field. Going forward, make sure that only English letters and numbers are allowed.
2. Currently, only 3 letter long abbreviation names are allowed. Going forward, make sure that 1-3 character long strings are allowed.

**Comment by eltang** [comment]
I was thinking about this issue and maybe the three-letter limit is not needed. The display can show a word longer than three letters by scrolling through it repeatedly.

**Comment by mondalaci** [comment]
True, but I'm confident that it wouldn't be a great user experience. It's much more easier to look at the whole text at once than waiting for scrolling.

**Comment by TorC8** [comment]
I tend to agree that the scrolling is just plain bad UX.  That said, is there any reason not to allow spaces in the abbreviation?  The first reason to do so that comes to mind is to allow someone to place a short abbreviation where they want it on the display.  Of course, perhaps this isn't a good idea if something like "x y" will cause problems.  Pretty minor, and not essential if the spaces are a problem.

**Comment by ert78gb** [comment]
I found the following line in the code https://github.com/UltimateHackingKeyboard/agent/blob/master/shared/src/store/reducers/user-configuration.ts#L277

```ts
const chars: string[] = '23456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
```

Is 1 directly missing from the chars array?

**Comment by mondalaci** [comment]
@ert78gb "1" should be included. This must be a bug. Would you please fix it? A simple commit to master would work.

**Comment by ert78gb** [comment]
I will do it in the issue PR

**Comment by mondalaci** [comment]
@TorC8 I think that allowing the abbreviation to be shorter than 3 characters makes more sense usability-wise than enabling the user to put a space anywhere. Let's say that the user creates a keymap of abbreviation " AB" and also "AB ". Keymaps of the same abbreviation are not allowed, and these look like the same, but they aren't. As for allowing space in the middle, maybe that wouldn't cause any misunderstandings, but it seems rather weird to me. Given the above, I'd rather go with alphanumeric abbreviations of 1-3 characters.

**Comment by TorC8** [comment]
I'd really been considering the display difference between "AB " and " AB".  On second thought, if you want to offer that option, better would be to use the right tool for the job and have a justification option rather than allow spaces.  Or just pick one, and let some fanatic display tweaker add the option later.

**Comment by mondalaci** [comment]
@TorC8 I think left-aligning is a better idea because the distance between the icons and the text is constant this way. We might eventually add an alignment setting but let's deal with more critical issues now.

By the way, I'm wondering whether you're a backer. If so, please get in touch via support@ultimategadgetlabs.com because I'd like to put you on the pilot run list. (I haven't found any other way to let you know than GitHub comments.)

**Comment by TorC8** [comment]
Agreed that the issue of alignment is best ignored for now.  If people really care about it, there's a fair chance someone will write a patch.

I wrote you on the other.
