### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by ert78gb** [UltimateHackingKeyboard/agent#347]
What do you think if I add [prettier](https://github.com/prettier/prettier) to our Dev process?

**Comment by mondalaci** [comment]
I welcome everything that makes our development experience better. Any objections, @fjozsef, @attilacsanyi?

**Comment by fjozsef** [comment]
Personally I don't see why would it be necessary. What features do we need from it which isn't handled by tslint or auto format from a modern IDE?

**Comment by ert78gb** [comment]
It is not necessary. It is just an option. It is not just warning if the code is not match some rule, but it automaticaly fix it. And we are use different IDE, with different support of tslint and autoformat. It is a common cli to that could integrate as pre-hook commit and automaticaly fix some error.

**Comment by mondalaci** [comment]
I feel a bit uneasy about getting our code automatically formatted. Consider the following code:

```
enum Direction {
    Up   = 1,
    Down = 2,
    Left = 3,
    Righ = 4
}
```

I assume that prettier would kill the above, intentional alignment. This may not be a strong case against prettier, but it's the only one on my mind.

**Comment by mondalaci** [comment]
@ert78gb I've just seen the introductory video of prettier, and I'm confident that it's the way forward and it'll save us a lot of time on the long run. Please make Agent run on prettier! :)

**Comment by owlstead** [comment]
> 
> 
> I feel a bit uneasy about getting our code automatically formatted. Consider the following code:
> 
> ```
> enum Direction {
>     Up   = 1,
>     Down = 2,
>     Left = 3,
>     Righ = 4
> }
> ```
> 
> I assume that prettier would kill the above, intentional alignment. This may not be a strong case against prettier, but it's the only one on my mind.

Intentional alignment should not be used anyway. It's a maintainability nightmare. This is the day that development environments allow for renaming and other higher level functions to be used. For instance, if somebody noticed that `Righ` should be `Right` then you suddenly would have `4` being displayed one space to the right. Developers have other things to do than to insert indentation and then to maintain them indefinitely. End-of-line comments are sometimes even worse.

**Comment by attilacsanyi** [comment]
You can use prettier ignore.

I have these for all enums:

// prettier-ignoreexport enum MyActionTypes { Val1 = '[Feature] Value', ValXx2 = '[Feature] Longer value'}
I hope this helps.

Attila    On Thursday, 6 December 2018, 15:21:58 CET, owlstead <notifications@github.com> wrote:  
 
 

I feel a bit uneasy about getting our code automatically formatted. Consider the following code:
enum Direction {
    Up   = 1,
    Down = 2,
    Left = 3,
    Righ = 4
}

I assume that prettier would kill the above, intentional alignment. This may not be a strong case against prettier, but it's the only one on my mind.


Intentional alignment should not be used anyway. It's a maintainability nightmare. This is the day that development environments allow for renaming and other higher level functions to be used. For instance, if somebody noticed that Righ should be Right then you suddenly would have 4 being displayed one space to the right. Developers have other things to do than to insert indentation and then to maintain them indefinitely. End-of-line comments are sometimes even worse.

**Comment by laxu** [comment]
+1 for Prettier. I've used it in several Typescript projects so far without issues. It takes a lot of manual formatting and small bug fixing out when you don't need to worry about semicolons, indents etc.

Only thing I would suggest in setting it up is setting line width to 100 characters as it makes for more readable code.

**Comment by ert78gb** [comment]
I close this issue because our decision is not introducing Prettier in the project
