### ISSUE TITLE
Change the way names and abbreviations are generated for duplicate keymaps

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#363]
When duplicating a keymap, please generate the names as follows: "QWERTY" -> "QWERTY (2)" -> "QWERTY (3)". This is how it currently works for macros, but not for keymaps.

Regarding the abbreviations, please make it so: QTY -> QT2 -> QT3.

**Comment by ert78gb** [comment]
If we reach the 9 what will be next value of the keymap name? 10 or A, 
QWERTY (9) -> QWERTY (10) or QWERTY (9) -> QWERTY (A)
Currently I implemented the first version, but the abbreviation will be A so I would like to know how would you like.

what is the expected behavior when  "QWERTY" -> "QWERTY (2)" -> "QWERTY (3)" exists and the user duplicate the "QWERTY (2)" -> "QWERTY (4)" or "QWERTY (2) (2)"
I implemented the first version currently.

**Comment by ert78gb** [comment]
Other use case:
"QWERTY" -> "QWERTY (2)" -> "QWERTY (3)"  exists and I modify the name of the second keymap "QWERTY (2)" -> "QWERTY", but QWERTY is exists what should do?

**Comment by mondalaci** [comment]
Regarding your first comment, I agree with both of your decisions.

Regarding your second comment, if an already existing keymap name, keymap abbreviation, or macro name gets entered, I'd rather like the editing to be cancelled and the original name to be restored.

**Comment by ert78gb** [comment]
> Regarding your second comment, if an already existing keymap name, keymap abbreviation, or macro name gets entered, I'd rather like the editing to be cancelled and the original name to be restored.

Ok I will do it
