### ISSUE TITLE
Less than 3 letter abbreviation throw serialization error

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#379]
1. Rename the abbreviation of one of your keymaps to an abbreviation of less than 3 characters
2. Transfer your configuration to the UHK (with ctrl+o for the time being)
3. Agent throws the following error:

![agent-error](https://user-images.githubusercontent.com/300402/28848221-6f500be0-7712-11e7-920b-651b45cd9c8d.png)

**Comment by fjozsef** [comment]
The bug should had been introduced with this https://github.com/UltimateHackingKeyboard/agent/commit/aad0c155dd5753bf8741d411c9a07da7762069e5#diff-7d1f3502a4574837a2c0c5beaed84f5fL59 
 @ert78gb I really don't know why were those lines deleted. What is that duplication logic there? Why don't we check just the abbreviation? Why is name involved?

**Comment by ert78gb** [comment]
Every time we have 2 properties name and abbreviation and the user only could modify only the one value at once. If the user change one value I use the other value to detect the duplication. 
This was my idea how to solve #363 issue.

**Comment by fjozsef** [comment]
Oh, I haven't checked the comments, just the main description. Maybe these kind of informations should be documented somewhere, because I wasn't aware unil now that the names are unique. 
(@mondalaci If you could add all the details from now to the opening comment of the issue, then it would be nice.)

@ert78gb Were the mentioned lines removed intentionally or should we just add them back?

**Comment by ert78gb** [comment]
I checked the Keymap.renameKeymap and I think we could add back.

**Comment by mondalaci** [comment]
@fjozsef Sorry about the confusion. I'll do my best!
