### ISSUE TITLE
Select lists in angular2

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#45]
On the mockups we have been using the [select2 jQuery library](https://select2.github.io/).

When @fjozsef started the implementation of the app in angular2, it turned out that there's no extension for select2. We have to find out a way how to deal with select list in the angular2 based app.

Below is a list of features we are using from the _select2_ library:
1. [templating](https://select2.github.io/examples.html#templating)
2. search box (optionally with customized searches)
3. themeable markup (the standard select element has limited theme support)

We are also using `<optgroup>` which is an HTML element for grouping the `<option>` elements of a `<select>`.

Discussing the situation with @fjozsef we found the following solutions:
1. make a wrapper of the jQuery select2 library in angular2. We've tried it out based on [this](https://github.com/liranyogev/angular2-examples/blob/master/select2.ts). It's *working* but we think it's *not elegant*.
2. [ng2-select](http://valor-software.com/ng2-select/) looked quite promising until we found out a bug in it's search (try searching for "bu" and see results, then try for "bud" and see the result). And this implementation is also tied to an older angular2 version (_2.0.0-beta.15_) but we are currently using the _rc1_ release.

### Decision points
1. What features we would like to use in a select list?
2. If we really need the features we are using now and we don't want to wrap jQuery plugins into angular2, can we split the features up in multiple rounds? (e.g. creating a custom angular2 implementation of a select list and add some filter capability later..)

**Comment by mondalaci** [comment]
@csanyiarpad @fjozsef I think that select2 should be wrapped into an ng2 component according to the Angular way. Also, I'd vote for maximum code reuse, and thus using ng2-select. How about forking it, fixing the issue, and sending a PR to them? That could result in miminum effort, and we'd also improve the ecosystem that way. Our forked repo could be featured in packages.json until our fix gets merged into their repo, at which point we could reference their repo instead.

I'd rule out the possibility of creating a custom select2-like implementation - countless hours have been put into select2 which we won't be able to replicate in any reasonable timeframe.

**Comment by NejcZdovc** [comment]
HI guys do you need any help with this? I would like to help also on other issues that you have in backlog regarding agent program.

**Comment by fjozsef** [comment]
We also shouldn't forget the fact that select2 doesn't support Typescript's module loading system. So we can only load it in the javascript way by adding the js and css to the html. Or do you know any other way?

If we want to use ng2-select then we have to wait until they upgrade to angular2-rc.1. (There is a pending pr for this.) About the search bug, we should check their search system, if they use other library for searching, then locating the bug can be difficult.

**Comment by fjozsef** [comment]
Hi @NejcZdovc, thank you for reaching us.
If you would like to contribiute then solving this issue could be your task. We would like to have a select2 component similar we have in the mockup, but in angular 2.
Feel free to ask if you have any question.
If you're done then you can send a PR :)

**Comment by NejcZdovc** [comment]
Hi, great I can do this. You were mentioning that you are waiting for ng2-select to reach RC version of angular2. I tried pull request that you mentioned, but it is not working correctly. So would you like it from me to work on existing ng2-select and port it to RC version or create wrapper for real select2 ([https://select2.github.io/](https://select2.github.io/)) for angular2?

**Comment by fjozsef** [comment]
I think first a select2 wrap would be enough and later we will change to ng2-select or create our own select component in ng2.

What do you think about [this](https://github.com/liranyogev/angular2-examples/blob/master/select2.ts) which was mentioned in the opening post? You can try to use it and create selects like we have in the mockup. If it doesn't fit our needs then you can start to create own wrapper.

**Comment by NejcZdovc** [comment]
Like already @csanyiarpad said this approach is not really elegant. Let me work on this issue today/tomorrow and prepare demo. You can then look at it and say if this is the right way to go or what to improve. Sound good?

**Comment by fjozsef** [comment]
@NejcZdovc You are totally right. In the future we either don't want to use library whose don't support external module loading.
For now we have lots of other things to do, so I thought if we have any select2 component then it's fine. Later, but before the release we could do the polishing. 

Demo: Okay. Take your time with it.

**Comment by NejcZdovc** [comment]
So I prepared small demo with select2 wraper. You can find it in [my repo](https://github.com/NejcZdovc/ng2-select2). It is done with Angular CLI. This component can be easily ported to agent.

I only implemented width and template management, features that are mentioned in first comment. It's very easy to extend this to all needed options. Component needs some more optimization and polishing, but I wanted to share it with you first, to see if this is something that you had in mind. It's very easy to reuse like @mondalaci wanted.

**Comment by mondalaci** [comment]
Thank you so much for your contribution, @NejcZdovc! I'm not qualified enough Angular-wise to comment on your select2 wrapper (which I leave it up to @fjozsef), but I wanted to voice our appreciation. If this turns out to be an ongoing effort on your part then we'll try to find a way to return the favor. ;)

Keep on rocking!

**Comment by NejcZdovc** [comment]
@mondalaci Not a problem. Hope @fjozsef will have a positive feedback :). In the mean time, do you need any more help regarding Angular 2. I love writing Angular 2 apps and would love to contribute to the project even more. Let me know.

**Comment by mondalaci** [comment]
@NejcZdovc Sure thing! We always welcome contributors, and glad you're interested! @fjozsef is rather busy on this week, but let us figure out what parts of Agent make sense to delegate. We'd love to get you involved. :)

We'll follow up, I promise.

**Comment by fjozsef** [comment]
@NejcZdovc The direction is good, but I think there are some features we need which couldn't work in this solution.

The select2 component should support option groups and images with text as option's child and maybe other kind of lists/list items later.
So the select2 can't assume that it has to show only options with text. I think the select2 should process its children so we can write something like this when we would like to use a select2:

```
<select2>
    <optgroup label="Example">
        <option>Text</option>
        <option><img src="..."/> Text 2</option>
    </optgroup>
</select2>
```

I think you should use ng-content and/or ContentChildren in the implementation.

Could you manage these modifications? Ask if you have any question :)

**Comment by NejcZdovc** [comment]
@fjozsef Sure, options groups was on roadmap to implement, but first I wanted to show you in which direction I wanted to go. That's why I created simple demo with first level for options.

I am not sure that I totally agree with this approach that you mentioned. Most of the times data for select is returned from ajax request or some JSON. That's why I would go with data binding as input and passing template to select2, rather than always writing down option, text, variables etc. It would be easier to just create json and bind it to component with appropriate template and that's it. Json that is passed to select2 as input is totally customizable so you can do whatever you want, because you can control output with template. So I would stay with this approach and implement rest of the logic to support things that I am talking about. What do you think?

**Comment by fjozsef** [comment]
I am not sure that an option which is passed as a property can be as customizable than the one which is passed inside of HTML. (But maybe I just miss something). I am worried about the options with images. What if we want to add two image not only one? What is we want want to color the text? 
For now with your approach we will be able to support the cases we have know, but I don't know if it covers all the cases we'll have later.

We both have static lists (layers: mod, fn, mouse) and dynamic lists (list of macros/keymaps). I think the first one would be cleaner if it would be hard coded. However I am not sure about the second one, if we want to pass arrays then we could use `*ngFor`, so we have to bind only 'once'.

Could you create a pros-cons list and compare both approach?

**Comment by NejcZdovc** [comment]
Let me upgrade my demo to more complex example, that will cover examples that you pointed out. It will also show how can be used for future cases.

**Comment by fjozsef** [comment]
Okay, let's see :)

**Comment by NejcZdovc** [comment]
Hi, finally had some time to improve demo. Please check it [out](https://github.com/NejcZdovc/ng2-select2).

In new demo I implemented direct generation of basic select element via **data** option from [select2 options](https://select2.github.io/options.html#data-adapters). This way I can now create anything, using basic data adapter and even add something additional. All additional data is directly accessible in select2 templates, so can be used in HTML generation. Everything that is supported in select 2 is now possible in this wrapper.

I also implemented data service. This approach can be also used in this project, because this way you have all data in one place (or maybe more if we create separate services for components), which is more readable and easy to update then hard coded data. I also implemented **optgroup** with select2 data option.

If you would like to add image for example to option it's very easy. Add member image or src (name can be anything) to additional object in data JSON. Now you just need to create templateResult and  templateSelection functions which will create custom HTML for option with image. This functions needs to be then added as input to select2 selector and that's it (demo is in repository for this example).

Hope that this more complex demo will show you why I wanted to implement things less hard coded. Component is easily reusable in customizable. What do you think?

P.S.: I am thinking to add other options (not just width) of select2 to this wrapper. Do you think that we need all of them or just few? I was thinking to prepare solution that will support dynamic loading of options via inputs. This way select2 can be used as we like it in the future :)

**Comment by fjozsef** [comment]
@NejcZdovc I have checked your code and I am amazed :) I have never used select2 before (so I can't tell if we need other options like width), but now as I as see the `templateResult` and `templateSelection` functions in action I think I am satisfied with this approach. Thank you so much for the research! :)

For me it's clear that you understand better than me how these work. So what do you think, can we/you know jump into the implementation of select2s we need or should we try other approaches?

**Comment by NejcZdovc** [comment]
Sure I can implement this without any problem. Before I start I have some suggestion regarding baseline, but let's start talk about this in another issue. #54

**Comment by fjozsef** [comment]
Answering https://github.com/UltimateHackingKeyboard/agent/issues/54#issuecomment-223794448 here. I think if ng2-select knows everything we need then we should use it over a wrapper. What do you think @mondalaci ?

**Comment by mondalaci** [comment]
You're right, I should have written my comment here, but Nejc has already answered there so I continued commenting over there. Copy-pasting the relevant part of my comment:

I'm a bit afraid that in the future we might use additional features which select2.js supports but select2.ts doesn't at which point we should wrap select2.js, but for the time being it makes sense to use select2.ts as long as it fits our needs out of the box.

**Comment by NejcZdovc** [comment]
I think that we are back at the beginning. So let's start from scratch. Will we totally remove jQuery in the next year? If no (because of Bootstrap or some other reason), I would stick with wrappers for jQuery plugins, because they are a lot more powerful then pure TypeScript plugins right now. Maybe this will change in the future, but for now it's not looking good. If yes, then we should use TypeScript implementation. That's it I think.

**Comment by mondalaci** [comment]
@NejcZdovc We will hardly remove jQuery in the next year, or ever. The jQuery ecosystem is immensely rich, and it won't go away anytime soon, so it'd make sense to cherry-pick useful jQuery plugins in the future and use them instead of writing stuff from scratch.

Given the above mindset, I agree that it'd make practical sense to wrap select2.js. Do you have any objections, @fjozsef?

Lastly, sorry for my initial oversight regarding JS vs TS select2 variatns. I'll try to be more observant in the future.

**Comment by fjozsef** [comment]
My problem with jQuery that it's not fit into the whole typescript & angular 2 philosophy.
-  It doesn't support external module loading of typescript, so we can't use it elegantly (lazy loading is also impossible, luckily we don't want to lazy load), which can lead to maintenance issues.
- It manipulates the dom directly without notifying angular, which uses virtual dom and would like to control the dom itself (to optimize rendering), which can lead to performance issues.

First (two) minute: [Angular 2 Tutorial (2016) - Angular 2 & jQuery (use with caution!)](https://www.youtube.com/watch?v=vrdHEBkGAow)
"Widespread use of jQuery is generally not a good idea in the context of Angular since it kind of goes against the spirit of Angular and other MVC frameworks. ... That said, there are still a few acceptable uses cases for jQuery in Angular. One such example is jQuery plugins." [Source](http://www.syntaxsuccess.com/viewarticle/using-jquery-with-angular-2.0)

So relying on it in this year is acceptable and probably in the next year, too. But I think we should have to eliminate it when it becomes possible. 

I understand that you are against the ng2-select2 because it doesn't support fully select2, but I think it's just matter of time and if we really need a feature we still have the option to send a PR to them.

Finally, I suggest to use the wrapper for now, but if we will have resources  in the end of the year then we should consider ng2-select2 or other alternative.

**Comment by mondalaci** [comment]
@fjozsef I fully understand where you're coming from. I also watched the video.

From an ideological standpoint we shouldn't use jQuery at all due to the reasons you mentioned. But from a practical standpoint we should.

It's not just the feature set of select2.js but its maturity. Thousands of man-hours have been spent on not only making it featureful but stable, and there are loads of jQuery plugins like that. I think the usefulness of these plugins outweight the incovenience of the lack of external module loading.

As for wrapping jQuery plugins into components, I've written about a dozen Angular 1 components like that and all of them worked without any issues. The trick was to wrap the HTML element to be transformed into a div or span. That way the data-binding of Angular is not messed with.

I support ditching jQuery in the far future but it's still going very strong.

**Comment by usmanwalana** [comment]
Reading through your comments, I got to know that you people have worked really hard to implement select2 functionality in angular2. I am developing an angular2 app. I am in DESPARETE need of this feature. I am using angular 2.0 final version. I have tried ng2-select but it only loads static data, I am loading data from webservice through Observable . I also tried ng2-select2 from @NejcZdovc  repository but could not set it up properly. I have googled and posted on forums but no luck. I believe you can guide me in the right direction. I just need a plugin which can search through data loaded through web service.

**Comment by mondalaci** [comment]
@usmanwalana It'd be useful if you could:

1. upload your code to a GitHub repo (preferably a minimal Angular 2 app featuring select2)
2. start a separate issue there, mention us, and describe exactly what's not working

I'm sure Nejc or Jozsef will try to help you if you make it very easy to help.

**Comment by NejcZdovc** [comment]
@usmanwalana Can you please crate an issue on https://github.com/NejcZdovc/ng2-select2 and I will try to help you out. As @mondalaci already suggested, create a small plnkr or github repo with your example.

**Comment by usmanwalana** [comment]
Dear @mondalaci and @NejcZdovc Thank you for your responses. I very much appreciate it. I have created an [issue in my repo](https://github.com/usmanwalana/ng2-select2/issues/1). I would be very grateful if you have a look at it and guide me what to do. I am new to angular2 development and any help or guidance would be appreciated. Thank you
