### ISSUE TITLE
Undefined in URL upon multiple keymap duplication

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#465]
When duplicating the QWERTY keymap many times and arriving to "QWERTY (35)", the URL goes "http://localhost/uhk/agent/packages/uhk-web/dist/#/keymap/QWundefined"

**Comment by ert78gb** [comment]
What is the expected behavior? The counter running out from available range. The software use `23456789ABCDEFGHIJKLMNOPQRSTUVWXYZ` values to increment the last character.
If the software run out of the last character range allow to increment the last before character.
After the QWZ the new abbreviation will QX1. Is it acceptable?

**Comment by mondalaci** [comment]
Yes, the suggested behavior would work great.
