### ISSUE TITLE
Keymap editor layer slider pills

### ISSUE THREAD

**Issue by csanyiarpad** [UltimateHackingKeyboard/agent#50]
Add label "Layers:" before the pill button is way that it's not touching the current center alignment of the buttons. `:before` content

**Comment by csanyiarpad** [comment]
@mondalaci can you review if this is something you thought about?

**Comment by mondalaci** [comment]
Looks pretty good, but the buttons as a group do not seem to be fully centralized compared to center of the keyboard. But I guess the center of the keyboard is elusive, as it's asymmetric, so the eye is tricked, and it may be perfect geometrically as it is. Let's not use a magic ratio just because of the asymmetry of the current UHK model. 50% should be fine.

Seems like there is no margin behind the buttons.

![ultimate hacking keyboard configurator](https://cloud.githubusercontent.com/assets/300402/15520070/c19d20ae-2204-11e6-8383-63931a0e9700.png)

**Comment by NejcZdovc** [comment]
What about adding text at the top, not on the left?

**Comment by mondalaci** [comment]
We have way more horizontal than vertical space, so I'd vote for left alignment.

**Comment by NejcZdovc** [comment]
When I was testing [agent](http://ultimatehackingkeyboard.github.io/agent/), I notice that image is not square, so this means that there will always be more space at the top and the bottom of the page (width of the keyboard is larger then height). That's why I thought that there could be easily some space for text at the top of the buttons.

Example for the resolution 1024px:
![image](https://cloud.githubusercontent.com/assets/9574457/15541432/c0e5cef8-228c-11e6-89a0-bff194c6f6d8.png)

And full screen without left menu:
![image](https://cloud.githubusercontent.com/assets/9574457/15541455/d735c852-228c-11e6-9ed7-8b5899559a7c.png)

**Comment by mondalaci** [comment]
True, but there will also be a fair amount content below the keyboard which
justifies the use of horizontal space.

**Comment by NejcZdovc** [comment]
Ok, that is something that was not aware and is not in demo. It's not great from design view, but from practical it's. Agree with you now :)
