### ISSUE TITLE
OSX Special key support (Brightness, Mission Control)

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/agent#538]
It would be nice if the  OSX keymaps supported the Mac special keys

- [ ] Brightness
- [ ] Mission Control (Formerly called Expose)
- [ ] Launchpad
- [ ] Desktop

https://apple.stackexchange.com/a/16624/48948

https://apple.stackexchange.com/questions/188091/find-out-what-key-code-brightness-up-down-has

http://macbiblioblog.blogspot.com/2014/12/key-codes-for-function-and-special-keys.html

|action|key code|function key|
| --- | --- | --- | 
|brightness up| 107|F14|
|brightness down| 113|F15|
|Mission Control|160|?|
|Launchpad|131|?|
|Desktop|103|F11|

This blog post has some good explanations on key codes, 
http://eastmanreference.com/complete-list-of-applescript-key-codes/

**Comment by mondalaci** [comment]
I temporarily modified Agent to try scancodes 160 and 131 of both the regular USB keyboard page and the consumer USB keyboard page and none of them had any effect on my Mac. I don't know about the referenced documents, but they may not mean USB scancodes but some other kinds of key codes which are possibly internal to OSX.

The other keys work as expected on Mac, but I rather wouldn't make them part of the default Mac keymaps (actually, F11 is mapped by default) because the relevant functions are not available on other OSes, so the various OS keymaps would be inconsistent.

Also, I think making Agent display F11, F14 and F15 as Desktop, Brightness Up, and Brightness Down is not a good idea. As a rule of thumb, Agent displays the simplest, universal representation of the scancodes, and not their OS-specific representation which can be misinterpreted by users when hooking up their UHKs to a computer that runs another OS.

Given the above, I'm closing this issue. Mac users, feel free to use F11, F14, and F15. Every one of these are mappable in Agent.
