### ISSUE TITLE
Angular enviorment

### ISSUE THREAD

**Issue by NejcZdovc** [UltimateHackingKeyboard/agent#54]
Before I start implementing select2 into the project if you don't mind explaining to me how are you developing this angular app, what is your flow? Which code style are you using? I saw that HTML from @csanyiarpad is in the same root as Angular app and you need to remove display none from angular elements to see how it works. So when you are developing new component you always need to remove display none from component to see it on page and hide basic html, to see only angular? Am I missing something or it's like this? @fjozsef

**Comment by fjozsef** [comment]
We are actually in the middle of migration to angular 2. As you can see the original code created by @csanyiarpad is in jQuery. It was just an experimenting to create a demo, how will the agent look like in the future. Now I am the responsible for make things work in angular 2. I try to follow the mockup when I implement but of course there are new features which will be introduced in angular 2 in the first place.

As I am concerned the display: none is just a trick to switch between pages, but later the whole menu will be in angular 2 and I would like to eliminate jQuery as much as possible.

About code style: I try to follow the [angular 2 style guide](https://angular.io/docs/ts/latest/guide/style-guide.html) but there are other expectations from @mondalaci maybe he can tell about it more, but basically the tslinter tells you what is wrong.

**Comment by mondalaci** [comment]
Well said, @fjozsef! `npm run lint` should do the trick. Eventually, we should also lint scss files. No other expectations beyond that.

**Comment by NejcZdovc** [comment]
Great. If you don't mind I have a few suggestions on which I can work this weekend. I spend a lot of time at my current company optimizing work flow and preparing projects seeds.

**Suggestions**
1. Remove all non angular (hard coded) elements from the project
2. Add Angular CLI to the project
3. Add all needed linters
4. Add testing tools and test coverage

**Explanation of suggestions:**
1. If we remove all non related code from the project it would be faster to code and less confusing. I don't want to remove jQuery, but hard coded HTML and CSS that was copied from the @csanyiarpad code. This way you can easily add new things and coding speed can improve.
2. Adding CLI to the project can standardize code with style guides and core concepts that are driven by Angular core team. I saw that you are using Webpack for generating SVG, which can be easily added to the CLI project.
3. With CLI you already get linters for TypeScript and Angular code style, but like @mondalaci mentioned there is also need for the SCSS. I am using Google's coding style for SCSS.
4. I know that you were also thinking about unit testing, but didn't have the time. I would suggest to slowly build code coverage with test (Karma and Jasmin).

I can work on all 4 points this weekend if you would like it and port current project to the CLI way. What do you think @mondalaci and @fjozsef?

**Comment by mondalaci** [comment]
@NejcZdovc What do I think? I think you're a godsent! :)

1. I'm all for totally moving to Angular 2, but I'd like to keep every part of the UI accessible, so that interested parties can see it, and play around with it. I'd prefer gradually moving to Angular without making any part of the UI inaccessible.
2. It's always great to increase the consistency and standardize the codebase of the project, so Angular CLI sounds like a great idea. My only fear is that we add yet another build dependency to the project which further complicates our toolchain while offering moderate benefits. I'd like to keep Agent easy to hack, and an overly complex toolchain can be a discouraging for newcomers. I'd like to hear @fjozsef's opinion on this, too.
3. Sounds good to me. What's your take on this, @csanyiarpad?
4. Totally agreed, but I'm afraid that building code coverage might take too much resources in the beginning when the codebase is in heavy flux. Wouldn't it be a better idea to build code coverage once the codebase settles a bit?

So glad you're on board!

**Comment by NejcZdovc** [comment]
Thank you for the feedback.

1. The problem with gradually moving to Angular is that code can be very messy and hard to control in the meantime. Don't you already have gh-page branch where all UI functionalities are laid down and everyone can see everything?

2. It's not really another building dependency, it's the only one :) You get everything that you need for the project from it. If you have any additional requirements you can easily extend it. Why I like to use it? On Angular2 scene there is a million seeds. And it's quite hard to work on projects when someone is using [systemjs](https://github.com/mgechev/angular2-seed), other [webpack](https://github.com/AngularClass/angular2-webpack-starter), someone is using yet another building tool. Every time you need to learn a new way of structure, config files etc. That's why I love CLI. It's driven by core team, it's based on official coding styles and it's very simple. And it's official. Every newcomer can very easily learn basic logic behind it and probably should. It can help you create components, routes, etc with ease. [Here ](https://github.com/NejcZdovc/ng2-select2/blob/master/package.json) you can see what dependencies are added when you are using CLI initialization of the project.

4. That really depends on programmer. If you are TDD then you insist on write test for every single thing from the beginning. It has quite some benefits, but it's quite time consuming. I personally adopt tests to the project. If you can afford test write as much test as possible, otherwise just core main and basic functionalities and later add full coverage when first phases are done. I would do the same here. Cover basic components with basic test and in spare time build coverage to the magic 100% :).

**Comment by NejcZdovc** [comment]
@mondalaci @fjozsef Can I start working on this?

**Comment by mondalaci** [comment]
@NejcZdovc Sorry for the delay! Please let me talk to @fjozsef first. I'm afraid that implementing all the suggested points at once would bring too much change over a short period of time, leading to a lot of discomfort. Maybe we should carry them out one after another in a slower pace. Please let us think about this for a bit.

In the meantime, you're welcome to work on the select2 component. I'm not exactly sure about its status.

After select2, it'd be also great if you could port the side menu to Angular.

Thank you, and we'll get back to you soon, I promise.

**Comment by NejcZdovc** [comment]
Sure not a problem, no pressure. I will implement select2 component (it's finished) and after that work on side menu.

**Comment by mondalaci** [comment]
@NejcZdovc Just talked to @fjozsef. Please let me share the details.

1. We'd like to keep the existing jQuery codebase for the time being, and gradually convert it to components one by one. @csanyiarpad is on its way to learn Angular 2, so he'll create Angular 2 components in the near future. From that point on no additional jQuery code will be written, so the jQuery codebase will gradually fade away as it gets converted to Angular 2.
2. We'd like to wait with the CLI migration until Agent is fully componentized. Before the migration we'd also like to evaluate CLI whether it fits our needs. We're afraid that its highly opinionated conventions would force us to do things differently than we normally would. We're also not sure whether it supports everything we want (and will want) to do that is now carried out by gulp and webpack.
3. @fjozsef and @csanyiarpad will extend our existing lint task with sass lint. There are more linters to choose from and I'd like to make sure that the right one gets choosen. It's a very small task so it probably doesn't make much sense to delegate.
4. We'd like to introduce testing once the codebase becomes more stable because maintaining the test cases would pose a significant overhead, and Agent is too much in flux nowadays.

As for the [external select2 component](https://github.com/valor-software/ng2-select), we've noticed that it's going strong nowadays, and they updated to the latest Angular 2. Given its momentum, it'd make sense to use it. What do you think? If you prefer your component would you elaborate why yours is a better choice?

Componentizing the side menu would be yet another glorious task for you. You're welcome to create an issue for it if you get there to discuss the details.

Thank you!

**Comment by NejcZdovc** [comment]
Hi thank you for the feedback. I agree with you I would use non jQuery select2 if it's possible. Now that they fixed RC1 problem it smart to implement it. I will then implement this select2 and then switch to side menu.

**Comment by mondalaci** [comment]
It has just occurred to me that it's not a select2 JS wrapper but a pure TypeScript implementation. I'm wondering why not just wrap the JS version. I don't foresee the TS version being as well supported as the JS version ever.

**Comment by NejcZdovc** [comment]
That's correct. Please referee to this [comment](https://github.com/UltimateHackingKeyboard/agent/issues/45#issuecomment-219345666). ng2-select is pure TypeScript component and it's not as powerful as Select2. But as @fjozsef said he would like to remove jQuery from the project. Because ng2-select was not ready at the time I created Select2 wrap for Angular2. So what should I do now? Implement my Select2 wrapper or ng2-select TypeScript component?

**Comment by fjozsef** [comment]
I think If the ng2-select knows everything we need then we should use it over a wrapper. What do you think @mondalaci ?

**Comment by mondalaci** [comment]
I see, thanks for explaining! Not depending directly on jQuery is realistic, not depending *indirectly* on it is not so much because it's used by Bootstrap, and there are bazillions of useful jQuery plugins in the wild. I'm a bit afraid that in the future we might use additional features which select2.js supports but select2.ts doesn't at which point we should wrap select2.js, but for the time being it makes sense to use select2.ts as long as it fits our needs out of the box.
