### ISSUE TITLE
User config update procedure

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#562]
This issue is quite heavy and needs to be rethought after implementing [firmware update notifications](https://github.com/UltimateHackingKeyboard/agent/issues/1666).

The user configuration of the UHK is a deep tree of objects serialized as a byte stream and stored in the EEPROM. If the format of the user config changes, it affects Agent's configuration serializer and the firmware's configuration parser.

We will have to change the user config format from time to time, and Agent must be able to transform any earlier version of the user config to the newest version to preserve the already existing configuration customized by the user.

1. Retrieve `oldMajorUserConfigVersion` from the user configuration of the UHK.
2. Retrieve `newMajorUserConfigVersion` from the `userConfigVersion` property of the top-level `package.json` of Agent.
3. If `oldMajorUserConfigVersion` > `newMajorUserConfigVersion` then display: "You must update to the latest Agent version." and an "Update Agent" button below.
4. If `newMajorUserConfigVersion` > `oldMajorUserConfigVersion` then transform the user config  from version `oldMajorUserConfigVersion` to `newMajorUserConfigVersion`. This may involve multiple transformation steps. Let's assume that the user config must be updated from version 3 to version 6. It gets updated using 3 transformation functions in sequence, namely from version 3->4, then 4->5, and 5->6.
5. If the new `userConfigSize` > `userConfigMaxSize` of `packages/usb/get-user-config-size.js` then display the following error message: "Agent tried to update your configuration, but it's too big to fit into the on-board memory of the UHK. This is an extremely rare situation. You must downgrade Agent to the previous version you used, delete a part of your configuration like a keymap or some macros, then upgrade to the latest Agent version and run it."
6. If the UHK firmware version is smaller than the package.json firmware version, then display a screen containing
"The firmware of your UHK must be updated." and an "Update firmware" button below.
7. If the package.json firmware version is smaller than the UHK firmware version, then display: "You must update to the latest Agent version." and an "Update Agent" button below.
8. If `newMajorUserConfigVersion` > `oldMajorUserConfigVersion` then write the new user config to the EEPROM and transfer it to the UHK as in `packages/usb/write-userconfig.js`.

**Comment by zx9w** [comment]
Hi, I didn't want to make a new issue for this since the name of this issue is perfect for what I would like to request.

Can we please have a cli that you can pipe the json config and it loads it into the keyboard?

It would make it so much more tractable to hack on this thing using the tools that are familiar rather than having to engage with the electron monstrosity every time you want to do anything (I understand that most ad-hoc stuff should be happening via dynamic stuff like macros or similar but having more tools gives freedom to express yourself however you feel is most idiomatic and for many of us the CLI is the ultimate idiom).

I wouldn't be opposed to building a small proof of concept if I knew the protocol that is being used to talk to the board and load the config (that you would still export from agent).

**Comment by mondalaci** [comment]
@zx9w Hi there! What you're proposing is quite different from this issue, but I understand your need. For now, you can build Agent and use the scripts in its packages/usb directory for such purposes.

**Comment by mondalaci** [comment]
This issue is already being implemented in #1682.
