### ISSUE TITLE
Serve releases from a CDN

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#565]
We received some complaints that downloading Agent releases is rather slow. I gave a try to some pull CDNs including Amazon Cloudfront, KeyCDN, and MaxCDN, and to my surprise neither of them cached the release files.

A KeyCDN staff member explained the reasons why. As it turns out, 1) GitHub releases redirect to Amazon S3 where they are actually stored instead of serving the release files directly. 2) The "Cache-Control: no-cache" is present in the response. 3) The Content-length HTTP header is not present but it should be greater than zero.

KeyCDN (and probably other pull CDNs) refuse to cache releases due to the above reasons. I think the best solution would be to set up a reverse proxy (maybe the nginx of ultimatehackingkeyboard.com) to proxy releases in a way that makes pull CDNs happy, then set up an origin in the CDN of our choice, and finally modify the javascript of https://ultimatehackingkeyboard.com/start/agent

I'd like to delegate the nginx setup and then do the rest.

**Comment by Jos512** [comment]
This is a good idea. But perhaps there are ways to do it easier with less time setting up and maintaining. 

I see that #553 talks about the `gh-pages` branch. If you include the release files in the GitHub pages website, you'll already benefit from a CDN. That's because Github pages are served with GitHub's own CDN ([source](https://github.com/blog/1715-faster-more-awesome-github-pages)). A GitHub pages site may be 1GB big ([source](https://help.github.com/articles/what-is-github-pages/)), so there should not be a problem with the release file taking up too much space. Alternatively you can always choose to only include the last 10 releases in the `gh-pages` branch, of course.

**Comment by mondalaci** [comment]
> @jos512 wrote: This is a good idea. But perhaps there are ways to do it easier with less time setting up and maintaining.
> 
> I see that #553 talks about the gh-pages branch. If you include the release files in the GitHub pages website, you'll already benefit from a CDN. That's because Github pages are served with GitHub's own CDN (source). A GitHub pages site may be 1GB big (source), so there should not be a problem with the release file taking up too much space. Alternatively you can always choose to only include the last 10 releases in the gh-pages branch, of course.

Thanks for the idea! Haven't thought of using GitHub Pages for this purpose yet. It's an interesting idea, and according to the testing I've just done it could work pretty well. If we'll ever use it, I think we should use another repo for releases because a single OS-specific Agent release occupies about 50M and the Agent repo would grow large very quickly.

GitHub Pages is surprisingly fast, and takes ~2s to download a 100MB file. I'd rather not delete older releases, so I'm not really in peace with the 1GB size constraint. Also, according to my knowledge a single file can't be larger than 100MB which shouldn't be a problem for now but it might be later.

Just for the sake of completeness, I mention that according to my testing GitHub Releases is backed by Amazon S3 whose bandwidth fluctuates quite wildly and it can be very slow at times, so it's out of question. (Also tested Cloudfront and it's not better for large files.)

Google Cloud Storage on the other hand seems to be the king of the hill because it consistently delivers 100MB/s transfer speed so I'd definitely pick it over the others.

**Comment by Jos512** [comment]
Thanks for your comment and enthusiasm. I removed my comment when I realised that all those releases should be kept in the repository for `gh-pages` to work, which makes cloning a painful operation. (If I realised that at the start, I wouldn't comment.)

But since you replied, I hope you don't mind me thinking along a bit more.

What you could also do is make a static html page that lists all recent downloads, and store that page with the downloads on S3 yourself, and then put Cloudflare in front of the static website on S3. That way you get the benefits from a CDN, but without the drawbacks of configuring and maintaining an additional server *and* without the drawback of paying CDN traffic fees. (Cloudflare's free plan works fine.)

Another option is not to change anything at all: when #250 gets implemented, the agent can download the files in the background. In that situation it doesn't matter that the download takes long, since the agent will only notify that the release is ready when downloaded.

Actually, it might be preferable to keep the Agent software downloads slow. That's because when you provide a quick and easy to find download for the Agent software, people might not wait for the application to auto-update but rather download it themselves. Especially when that special download page is feature prominently on the website and social media communications. 

But all that extra exposure to the latest high-speed download can put an extra stress on you and your team when there's a bug in the release.

If you nudge people to use the auto-update feature of the application (instead of offering a high-speed download), there's more control from your side to how the update rolls out. And people that absolutely need the latest download to fix a bug they have, they would probably also have the patience to wait 5 minutes for the download to complete given the personal significance the new release has for them.

(Sorry for the long response. I know your guys are busy enough already.)

**Comment by mondalaci** [comment]
Thanks for elaborating about this!

Given that the auto-update notification will show up in Agent after automatically downloading the update, GitHub releases should work perfectly.

The reason using a blazingly fast CDN still makes sense is that Agent has to be downloaded manually initially regardless, (as the last step of our onboarding procedure) and the download speed will affect the user experience. It'd probably make sense to only keep the last release on Google Cloud Storage and keep every release on GitHub Releases. As for paying for a CDN, money is not an issue, but user experience is.

**Comment by iprok** [comment]
I also think you should use some server or VPS with nginx for serving release files and proxy to it using cloudflare CDN. I've used in many my projects and it seems to feet your need for speed. You can automate process of puting release on the server and updating listing pages for all your releases.

I can help you in all this process if you need.

By the way as for me I don't like Google Cloud Storage because I can't download from it using direct link and wget, for examle.

**Comment by mondalaci** [comment]
Quickly downloading large files is my major concern regarding this issue, and according to my findings, Google Cloud Storage is the fastest CDN for large files by far. You're welcome to prove me wrong.

It is possible to download from Google Cloud Storage by using direct links.

**Comment by iprok** [comment]
If this files are less then 512MB (megabytes) size then you should test cloudflare CDN (not spam, I'm their free client, wanna help you). 512MB for one file is the only size limit they have.

Here is result of downloading agent files which I've put on my server behind CDN for you: 
https://quiterss.org/files/test/UHK.Agent-1.2.5-mac.1.2.5.dmg
https://quiterss.org/files/test/UHK.Agent-1.2.5-win.exe

Downloading to Russia (100 Mbit/s link client connection):
(9,86 MB/s) - «UHK.Agent-1.2.5-win.exe - full 100 Mbit/s

Downloading to France (1 Gbit/s link):
(44.7 MB/s) - ‘UHK.Agent-1.2.5-win.exe’ - 4 times more then 100 Mbit/s

Downloading to USA (1 Gbit/s link):
(66.4 MB/s) - ‘UHK.Agent-1.2.5-mac.1.2.5.dmg

Downloading to Germany (500 Mbit/s link):
(47.6 MB/s) - ‘UHK.Agent-1.2.5-mac.1.2.5.dmg

You are welcome to test downloading from the links above or I've created 300 megabytes full of random data file for you: https://quiterss.org/files/test/randomfile.bin . You can test high speed links using it.

**Comment by mondalaci** [comment]
Thanks for elaborating about this!

Done some tests, and it seems to me that the 100MB/s download speed of Google Cloud Storage is not as consistent as I thought. This time, it was more like 66MB/s, pretty much the same as Cloudflare's.

It also seems to me that download speeds may be slower initially until the release is cached by the edge location. I guess it's not surprising.

Given the above, I don't feel so strongly about Google Cloud Storage as I did before, although given our traffic, their pricing is probably better.

How would you implement this exactly?

**Comment by iprok** [comment]
@mondalaci first of all let's get clear about abbreviation meaning. Seems that 100 MB/s in your meaning are 100 megaBIT per second, and in my comment MB/s is megaBYTES per second. As far as I know MegaBytes are MB and MegaBits are Mb, so speed in my comment are near 100 Megabits/s to Russia and much more that 100 Megabits/s to all other location, cause cloudflare can give you near gigabits/s speed or may be more.

> It also seems to me that download speeds may be slower initially until the release is cached by the edge location. I guess it's not surprising.

If you place your files on server with good link (I know hosting provider where 1Gbit/s servers costs near 20 euro) it makes no sense cause it takes few seconds on 1 Gbit/s link to send even large file.

> Given the above, I don't feel so strongly about Google Cloud Storage as I did before, although given our traffic, their pricing is probably better.

As I get from the task free plan of cloudflare will be enough for you. You only need some server or VPS to place files on.

> How would you implement this exactly?

I need 1 server with linux and good internet link (100 Mbit/s at least, 1 Gbit/s will be much better). Then we should put on it any webserver which can serve static files. Apache is ok, but I preffer nginx. You need to upload files somehow (ftp/sftp etc) there.

Then you need to get accound on cloudflare with some domain name linked to it. Cloudflare should be NS hosting for this domain name to make proxing work. You don't need to transfer your main domain (https://ultimatehackingkeyboard.com/), but you can if you want (cloudflare is very stable NS hosting with handy interface) Any way you need to transfer some second level domain (example.com) to cloudflare. Your download links can be https://example.com/somefile or https://subdomain.example.com/somefile. Then you should set up proxing on cloudflare side and some headers on nginx side.

**Comment by mondalaci** [comment]
I actually meant megabytes when saying MB.

Just tested Google Cloud Storage vs Cloudflare (via your links), and the latter was so much faster! I'm sold. Cloudflare consistently delivered about 100MB/s.

In the setup that you're suggesting, Cloudflare would operate as a pull CDN, pulling files from our server, right? Any way to push to it instead? I'd much rather push to Cloudflare because then even initial downloads would be blazingly fast right after publishing a new release.

**Comment by iprok** [comment]
In short - no way to actually push to cloudflare *may be on corporate plan). But 
1) Just use server with fast link - nobody will notice difference between the first download and all others.
2) You can "warm up the caches" right after release - just download first.

**Comment by iprok** [comment]
I'm ok with the Linode. May be some issues from your host?

wget https://ultimatehackingkeyboard.com/UHK.Agent-1.2.5-linux-x86_64.AppImage     
--2018-07-08 22:39:12--  https://ultimatehackingkeyboard.com/UHK.Agent-1.2.5-linux-x86_64.AppImage
Resolving ultimatehackingkeyboard.com (ultimatehackingkeyboard.com)... 2a01:7e00::f03c:91ff:fe96:b4fc, 109.74.195.168
Connecting to ultimatehackingkeyboard.com (ultimatehackingkeyboard.com)|2a01:7e00::f03c:91ff:fe96:b4fc|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55113778 (53M) [application/octet-stream]
Saving to: ‘UHK.Agent-1.2.5-linux-x86_64.AppImage’

UHK.Agent-1.2.5-linux-x86_64.AppImage     100%[===================================================================================>]  52.56M  56.2MB/s    in 0.9s    

2018-07-08 22:39:13 (56.2 MB/s) - ‘UHK.Agent-1.2.5-linux-x86_64.AppImage’ saved [55113778/55113778]

Anyway I think cloudflare+Linode will be ok.

**Comment by mondalaci** [comment]
This is weird. I have a gigabit domestic connection and Cloudflare for example is blazingly fast. Maybe my ISP throttles Linode traffic. If Linode was so fast from everywhere, a CDN wouldn't be needed actually. Do you agree?

**Comment by iprok** [comment]
@mondalaci I agree. But VPS can't give you stable network quality as dedicated server do. And dedicated server can't give so quality as CDN can.
I don't know where is the problem between you and Linode, but as I've told earlier I'm sure that it will not be any problem between Linode and cloudflare. So you can use your VPS as backend for cloudflare.

**Comment by mondalaci** [comment]
Gotcha. I like your thinking, and will go with Cloudflare.

**Comment by mondalaci** [comment]
GitHub releases is very fast nowadays. I'm closing this issue and reopen if necessary.
