### ISSUE TITLE
Layout Print Option

### ISSUE THREAD

**Issue by kour1er** [UltimateHackingKeyboard/agent#575]
When creating a new layout, sometimes it can be difficult to remember exactly where you put everything. Would it be possible to add the ability to Agent to print out your custom keyboard layout as a paper guide? This could set next to your keyboard to aid quick lookups.

**Comment by mondalaci** [comment]
Thanks for the idea! This sounds useful, and we should do it eventually. I'll work out the details of the spec later.

**Comment by sad2project** [comment]
+1

**Comment by owlstead** [comment]
Alternatively / additionally an on-screen keyboard representation of the keyboard that shows the current layer of the keyboard would be very nice. It would be logical to re-use the keyboard image of Agent for this. I've not created a feature request on it because I can see that this is a relatively large and complex feature request (communicating between the keyboard modifier keys and the agent will be tricky). 

For now you can just capture screen shots of the Agent of course. Alt-PrtScrn is a relatively simple workaround for both ideas.

**Comment by redwards510** [comment]
I want this too, but it's pretty trivial to capture a screenshot using ShareX or something and print it out, so I don't expect it to be prioritized. What would be really nice is if you could consolidate all the layers on one page and print that out, since you can't do that with a screenshot. I think I'm going to enter a feature request that allow custom text on the keys in the layer picture, rather than just displaying the keys involved. This would help you remember the action performed when you bind a fancy key combo. Example: SHIFT + WIN + RIGHTARROW moves windows to other monitors. I'd like to see the text "MOVE WIN R" on that key in Agent rather than just the right arrow and the modifier keys..

**Comment by owlstead** [comment]
References of readwards510's and my feature requests:

#912
#913

**Comment by krokofant** [comment]
This sounds like an interesting feature to try and implement. Along with printing the layout it would be great if it was localized, similar to #710, but only when printing. Maybe this could be made somehow with ngx-translate.

I'll try to provide a proof of concept.

**Comment by mondalaci** [comment]
On second thought, I'd much rather go with an on-screen display for this. It'll be a lot more work, but it's a better solution. I'll create a specification later, and closing this issue now.
