### ISSUE TITLE
KeyMacroAction is broken

### ISSUE THREAD

**Issue by eltang** [UltimateHackingKeyboard/agent#612]
Currently, there are only 8 bits of space reserved for the scancode in the binary representation of a KeyMacroAction. Therefore, any KeyMacroAction with a scancode wider than 8 bits will not be converted correctly. This issue has not caused any symptoms due to the macro engine in the firmware being not yet operational, but it will need to be fixed before the macro engine is rolled out.

It might be a good idea to rename KeyMacroAction to KeystrokeMacroAction to make it consistent with KeystrokeAction.

**Comment by mondalaci** [comment]
@eltang Thanks for reporting this bug! It has been fixed both in Agent and the firmware.

Luckily, this bug doesn't affect exisiting user configurations because the default configuration doesn't contain long media keystroke macro actions, and agent hung when setting one (launch web browser, launch email client, or launch calculator).

Now you're free to rock and roll when it comes to the macro engine!
