### ISSUE TITLE
Provide reasonable default mouse settings for Macs

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#632]
Move the "Reset speeds to default" button on the Mouse Speed page below the "Mouse speed" title, and rename it to "Reset PC default speeds".

Make a new button rightwards of the "Reset PC default speeds" button and call it "Reset Mac default speeds". When clicking it, apply the following configuration options:

```
  "mouseMoveInitialSpeed": 8,
  "mouseMoveAcceleration": 180,
  "mouseMoveDeceleratedSpeed": 80,
  "mouseMoveBaseSpeed": 112,
  "mouseMoveAcceleratedSpeed": 160,
  "mouseScrollInitialSpeed": 10,
  "mouseScrollAcceleration": 10,
  "mouseScrollDeceleratedSpeed": 7,
  "mouseScrollBaseSpeed": 10,
  "mouseScrollAcceleratedSpeed": 12,
```

**Comment by mondalaci** [comment]
I rather wouldn't make mouse settings keymap-specific. At least not yet.

**Comment by reardencode** [comment]
As someone who uses the UHK with a Retina Mac, and a PC with 1080P monitors, I'd love to have the mouse settings be per keymap, or at least to have a keymap be able to override the defaults.

**Comment by kareltucek** [comment]
@reardencode shouldn't this usecase be handled on operating system level? I mean, theoretically, you can have multiple monitors connected to a computer and each one of them can have different DPI and therefore different "correct" pointer speeds...

**Comment by reardencode** [comment]
@kareltucek I believe that the problem is that what the OS considers a pixel is different between Mac and Windows/Linux. I don't know for sure, but I suspect Mac considers each pixel on the oversampled backing "screen" to be a pixel for mouse movement purposes, where PC/Linux consider each physical pixel only. (or something similar)

So what we really need isn't separate defaults per OS, or per-keymap settings, but rather a way for the keyboard to detect the host OS and change the mouse mode's behavior.

No idea if that's possible, so in the meantime, per-keymap mouse speeds would really make my life easier :( :)

**Comment by kareltucek** [comment]
I am afraid I still don't understand how that makes it a pointing-device's issue. You will have the same problem with a regular non-configurable mouse, or not? And in that case you will need to alter your OS settings, not to buy a new mouse. 

I think that the settings of UHK is rather targeted to allow tailoring the controls to resemble mouse on hardware level - since there's no clearly given and correct way to say "well, this and that speed corresponds to a light movement of wrist".

I mean, the request is probably still a reasonable one, but just because "it will make life easier", not because "some hardware setup requires it".

**Comment by kareltucek** [comment]
Anyway, it should suffice to allow changing `mouse_kinetic_state_t.intMultiplier` (could be added as a command in https://github.com/kareltucek/firmware ). Still, I don't like the idea since  it would make the settings feel even messier than they are now.

**Comment by reardencode** [comment]
Actually yes, I do find that hardware mice are also dramatically different between the OSs. It's just more tolerable because you can "just" move your wrist faster/further, vs. having to hold a key for more time.

Turning the mouse tracking speed to maximum in OSX has let me get UHK mouse behavior to be within reasonable ranges on both OSs that I use, so maybe changing UHK behavior is indeed not the right move.

**Comment by mondalaci** [comment]
@reardencode @kareltucek As you correctly noted, a lot of OS-specific variables are involved, such as pointer speed, acceleration profile, and default OS settings. Windows and Linux are pretty similar out of the box, but Mac differs a lot. In my mind, the main advantage of per-keymap mouse settings would be a better onboarding experience regarding mouse usage. Maybe we'll do it eventually, but it feels rather overkill right now.
