### ISSUE TITLE
Agent wants to set up Linux device permissions on MacOS

### ISSUE THREAD

**Issue by scottjl** [UltimateHackingKeyboard/agent#634]
Just received my UHK. Installed UHK Agent v1.2.0 MacOS X on MBP running 10.13.4. Launch Agent and receive a screen stating "Agent wasn't able to set up permissions via PolicyKit. This is most likely because the polkit package is not installed on your system." Followed by some commands that are clearly intended for a Linux based system and not MacOS X.

The keyboard appears to work, but I can't use the Agent application for any of it's intended features.

Help?

**Comment by mondalaci** [comment]
Sorry about this experience, and thanks for reporting! Agent almost always works well out of the box.

Please give [Agent 1.2.1](https://github.com/UltimateHackingKeyboard/agent/releases/tag/v1.2.1) a try that I've just released.

If the issue persists then please send the console log, so that we can look into it.

**Comment by scottjl** [comment]
This version is working as expected. Thank you!

**Comment by aki009** [comment]
I just received my UHK and it seems Agent 1.2.5 is having this same issue. I get the Linux instructions for polkit even this system is a Mac.

**Comment by mondalaci** [comment]
@aki009 This is rather strange. Would you also give it a try to Agent 1.2.1 - 1.2.4 and let me know which works (if any)?

**Comment by mondalaci** [comment]
@aki009 Please let's not comment in this issue anymore and jump to the other you opened.
