### ISSUE TITLE
Generalization of the "secondary role" feature. 

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#684]
I've been thinking a bit about use cases of the secondary role and I find the feature quite ingeneral. Namely I do not see a reason why secondary role should not be appliable to mouse actions and macros. Also the current behaviour does not allow binding modifiers to mouse actions. 

Proposed solution:
- add mouse actions (and possibly macro execution) into the 'Scancode' action list. (Leaving the mouse action tab as-is, for intuitiveness.)
- unify the conceptual understanding of scancodes and mouse actions 

Use cases motivating this request:
- using the mouse mod key also as a left click key
- zooming with a single key press (via binding ctr+scroll)

**Comment by mondalaci** [comment]
Practically speaking, it would only make sense to trigger macros as the primary role of a dual role actions given that mouse actions can be implemented by macros. And even then, usability would be limited because primary actions trigger momentarily upon key release, making drag and drop impossible this way.

I don't feel strongly about this one. I think it'd add a little value for few while introducing additional complexity. I'd rather reconsider this feature later according to user feedback. In the meantime, I'll close this issue and tag it as an "exotic feature" for later reconsideration.

You're welcome to keep this conversation rolling. I'll always follow up.

**Comment by kareltucek** [comment]
Drag&drop is a good point, yet personally, I would not miss it. (I can't think of a single scenario relevant for me.) Still modifiers for mouse actions sound possibly relevant.

I totally agree that there are currently more pressing issues, especially if this is not as simple to implement as it seems. Waiting for more feedback sounds reasonable.

**Comment by mondalaci** [comment]
Thanks for understanding! This issue would affect Agent, the firmware, and the binary configuration format, so it's not as trivial as it might seem. Let's wait for more feedback.
