### ISSUE TITLE
Support double-clicking to emit scancode

### ISSUE THREAD

**Issue by Ashod** [UltimateHackingKeyboard/agent#720]
I'm used to having caps-lock replaced with ESC. Of course with the UHK that's the mouse key.

A reasonable alternative is to issue ESC by double-clicking, say, the Shift key (since double-clicking the mouse key would lock it).

As I'm unable to find support for double-licking to activate/emit a given scancode (or indeed any command, in the future including macros too), I think it'd be a fine addition to the agent (I expect the core logic exists in the firmware already as double-licking to lock layers already exists in some form).

**Comment by mondalaci** [comment]
According to the feedback we've received, this is a very rarely requested feature. So far, only you've asked for it. If we implemented features like this, it'd make the UI of Agent very complex and hard to use, yet it'd likely not add value for other users. That's why I'm hesitant to add such features.

We'll reconsider this feature later when all of the planned features will get implemented. In the meantime, I'm closing it and tagging it as an exotic feature, meaning that it's a subject of future reconsideration.

You're welcome to follow up regardless of the closed state of the issue.

**Comment by Ashod** [comment]
@mondalaci thanks for the quick response. I understand what you mean. In my mind I imagined another entry below Scancode for this. Say "Double-click scancode". Although I guess modifiers for this double-click functionality would also be reasonable to have, though perhaps that can be omitted.

At any rate, it's not a deal breaker, especially when #617 gets implemented. But I do believe it will make the UHK quite power as double-clicking in itself will double all layers with a fast secondary functionality (per-key) that doesn't require an activation key. A killer feature for power-users!

**Comment by mondalaci** [comment]
Thanks for elaborating on it! I promise I'll reconsider once this madness (delivering the pre-orders) is over.

**Comment by Ashod** [comment]
@mondalaci Thanks much. I do appreciate that you have a backlog to go through (not least the modules, of which I have a couple on order). So no pressure.

Perhaps it might help to keep this open so others can show interest? Anyway, I'll it in your safe hands :)

**Comment by mondalaci** [comment]
I'd rather keep it closed for a while. The list of exotic features keeps growing, and I'd much rather prefer to concentrate on more pressing issues.

**Comment by pbartyik** [comment]
Instead of openinga new issue describing a similar thing I'd like to +1 this one :) With an additional idea:
- ability to bind modifier for tap-and-hold
I currently have 'mouse' remapped to Escape with ALT as secondary role (vim/tmux thing), with tap-and-hold I could set it to CTRL and wouldn't have to move my pinky finger that much :)

**Comment by kareltucek** [comment]
> I'd like to +1

If you dont mind getting your hands dirty with a "scriptish" implementation of macro engine, then binding actions to doubletap is possible with https://github.com/kareltucek/firmware

> ability to bind modifier for tap-and-hold

Regarding the second idea it would be a good idea to create a new ticket with a bit more elaborate description. Laci will probably close it as an exotic feature, but it will be possible to look up the idea using the label. No one will notice here.
