### ISSUE TITLE
Configuration history

### ISSUE THREAD

**Issue by Ashod** [UltimateHackingKeyboard/agent#722]
At first change the "Save to keyboard" blue button is visible at the bottom right. However how does one discard any changes (without closing and re-running the agent) ?

Would be very useful to have a "Discard changes" (red?) button when modifications are made so one can safely reset changes to what the keyboard has loaded, as though one restarted the agent.

**Comment by mondalaci** [comment]
You are right that currently there's no way to discard changes with the exception of keymap and macro delete operations without closing and re-running Agent, but I doubt the usability of this feature. Nobody requested it so far, and users typically change one key at a time, so it's easy to undo a change manually. What is your exact use case that justifies this feature?

**Comment by Ashod** [comment]
Making a modification without remembering what the original value was :)

In another case I found out that I had modified the wrong keymap and was easier to simple discard all changes rather than try to manually undo.

**Comment by mondalaci** [comment]
Gotcha. :)

Well, Agent is built upon a very powerful foundation when it comes to moving in its history. I think we can implement undo and redo very easily, but I don't want to pollute the UI with these rarely used features. How about binding Ctrl+Z to undo and Ctrl+Y to redo?

**Comment by luteijn** [comment]
Nobody requesting a feature doesn't mean they would like to have it ;) I assume/hope there's plenty of people that are just leaving their feature requests etc. for now to give you some air to finish deliveries and get more critical stuff sorted out. My ow preferred way to handle this would be by implementing import/export to file, so one can make their own back-ups, and if the file format is not too exotic, even just edit them with a different editor that has an undo function.

**Comment by kareltucek** [comment]
Well, the current behviour, i.e., when agent saves things on its own definitely is quite counter-intuitive. If I remember correctly, my original expectation was that changing keymap without saving would discard the keymap's changing. 

I think that Ctrl+Z/Y would be nice to have. However, I do not think that they are sufficient with respect to usability/intuitiveness. I think that there should be an explicit button so that the user knows he can do such a thing.

@luteijn the format is json - clean and easily understable. However, editing it by hand is not very practical. At the moment, you can export entire configuration (i.e., all keymaps in one file). The export/import of single keymaps is planned. (Export is already present in older agent versions.)

**Comment by mondalaci** [comment]
@luteijn Sure, but there's clearly a pattern. There are features that have been requested by couple of people. Importing/exporting the configuration is already possible in Agent.

@kareltucek The UI of Agent is exceptionally clean because no features like undo/redo are included. It's very easy to clutter the UI. We'll have a help page about the shortcuts. I'd much rather prefer only having undo/redo shortcuts for the time being. I can't see why the current way of saving is counter-intuitive. Every user found the save button so far and figured it out on their own which suggests to me that it's very intuitive.

**Comment by kareltucek** [comment]
Of course that every user finds out what a button actually does when he first clicks it... I believe the term intuitiveness refers rather to the ability of correctly expecting what a button would do when clicked. 

Especially any need to have a special pages about shortcuts goes against intuitiveness... How many users you know actually read manuals before using programs?

If the second sentence from the previous post is unclear, then my original expectation was that "save" would save the single keymap into the keyboard when clicked.  Therefore I assumed that switching to another keymap in the left pane would throw out any unsaved changes of the previous keymap. It is logical because spatially the save button is in the area which hierarchically belongs to a single keymap.

**Comment by mondalaci** [comment]
I don't expect users to read manuals which is the reason why Agent is so simple, and I'm dedicated to keep it that way. We won't make a manual, merely a simple help page mostly featuring a handful shortcuts.

Thanks for elaborating about the save button. Never thought of it this way which is unsurprising as the designer of the feature. I can't see any better way, though.

**Comment by kareltucek** [comment]
The point was definitely not whether you plan a manual or a help page. The point was that when a tip is at a different place than the feature, it is going to be missed by 90% of users. The only difference between a manual and a help page is whether it is 90% or 99%.

I do not consider this ticket very important, yet I think clean-with-respect-to-UI would be to make clear what is "unsaved" (e.g., by boldening an altered keymap in the left pane) and adding an explicit-and-visible discard button which would operate on per-keymap basis. 

However I really do not see this issue as crucial. Just sharing an opinion on what is intuitive and what is not ;-).

**Comment by IzK666** [comment]
I only use a single keymap, but I supposed that changing from one keymap to another will discard all changes done to the first one, because the save button is on the right side. IMHO, the save button should be attached to the current keymap/mouse speed/any menu entry and ask you for saving or discarding if you change to another menu entry.

**Comment by mondalaci** [comment]
@TorC8 Your suggested modification wouldn't cover the valid use case when both checkboxes are checked, so let's stick to checkboxes instead of buttons.

**Comment by owlstead** [comment]
+1 for the feature request. I certainly want to undo stuff, and personally I think the saving should either be performed automatically (probably not a good idea for the flash / EEPROM) or there should be a cancel option. Note that having an OK and Cancel option is rather... normal for GUI design. And yes, checkboxes are also suitable IMHO.
