### ISSUE TITLE
Mapping of German Umlauts

### ISSUE THREAD

**Issue by mliebelt** [UltimateHackingKeyboard/agent#725]
I would like to switch the keyboard language to English, so I can type what I see. Currently I have a German windows, with a German keymap. The one thing I urgently need is to map the German umlauts (äöüÄÖÜß) to some other keys. I would like to use FN-a,FN-o, FN-u, .., FN-s) as mapping.

How can I do that? I tried it, with the UHK connected, and was not able to enter the value ä for the binding.

**Comment by mliebelt** [comment]
After searching around for "cursor", I found accidentally https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk

I gave it a try, and this is the result:

* Remapped FN-a, FN-o, and FN-u (see screenshot)
* Output in Vim looks like: `äÄ^°öÖ` (with the specialty that '^' was only omitted after typing FN-SHIFT-o.

So the mapping of FN-u goes to ö, and the mapping of FN-o does not work at all. I am stuck now ...

![image](https://user-images.githubusercontent.com/520039/42732720-7957689c-8826-11e8-89c2-03828a766c98.png)

**Comment by mliebelt** [comment]
Last comment: When I switch to en (US) keyboard, I just get the characters on the keyboard, and no German umlauts.

So current situation:
* Having de (DE) enabled, I can just type äöü by pressing ;,[
* Having de (DE) enabled, I can type FN-a, and get ä (which is great), but mapping of FN-o and FN-u just don't work.
* Haring en (US) enabled (which is my goal), I don't get any German Umlauts.

Seems I have to wait for macro support (and I hope that I am then able to "type" the German Umlaut by using ALT codes then).

**Comment by mliebelt** [comment]
Hi mondalaci,

thank`s for your reply. What do I have to do to get the mapping for äAöÖüÜ? At the moment, I am able to type them directly (German keyboard layout), what are the mappings then?

"Your Fn mappings seem to work as they should" ... is not exactly what I expected.

Bye
           Markus

**Comment by luteijn** [comment]
the keyboard basically sends which key you press/release to the OS. The OS maps the keys pressed to the characters to show or actions to take. It uses mapping tables for that. The one for the US doesn't include any accented or umlauted characters.
The usual way to type umlauts and accented characters with an american keyboard in The Netherlands (which does have a national keyboard layout, but almost no-one uses it in earnest, we normally are using the american layout instead, so the uhk layout is perfect for us), is to use the 'US-international' keyboard map, which has the accent keys work as dead keys. This might work for you too, although it is probably a little counter-intuitive to type the umlaut before the main letter (Schr"oder).

Note that many people here don't like dead keys as they mess with quoting in programming and just learn to live without accented characters on the keyboard and work around the issue with the equivalent of writing  Schroeder and/or put in the occasional accented character with an alt code, pasting it in, or temporarily switching to the US-int keymap.

**Comment by mliebelt** [comment]
This is exactly I was searching for, thank's for the explanation. I have switched now to US (international) and I will see how it works. Have to relearn a little bit, but I think it will be worth it.

**Comment by mondalaci** [comment]
Why wasn't this obvious based on https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk ?

I try hard to minimize communication overhead by writing guides like the above. Please let me know how  I can improve it.

**Comment by luteijn** [comment]
As I already have a bit more than average background knowledge on stuff like midi protocol, computer keyboards, ASCII, serial terminals, xt, at, ps/2, usb, key roll-over, scancode sets, key-repeat, national keyboard layouts, the evils of localization,  ansi<->iso and lots of other more or less related subjects Laci's 'faq'-explanation was enough for me, but everyone comes in with different prior knowledge.

**Comment by mondalaci** [comment]
@luteijn Thanks for the explanation, and the link to the scancode guide, but I'm afraid if people don't read or understand my short guide, they will surely be scared off  by such a long read.

**Comment by luteijn** [comment]
Depends on what the issue exactly is with your text. If it is 'too long, didn't read' then the fix would have to be to change it to something short and general, like "The Keyboard to Computer communication is not based on the keyboard telling the computer what letter/number or font is used, but what keys are pressed or released. The translation from keys to letters is done by the OS software on the computer. There can be several levels of translation, for example keyboard layout chosen, window-manager and application specific macro/hotkey settings and/or  something like autohotkey to give more automation e.g. to type a euro-sign when ctrl-alt-5 is typed. Besides its basic function of debouncing the keypresses & releases and reporting them to the OS, the UHK also adds a few levels of translation of its own, that make it possible to virtually move keys around, to switch between virtual layers and to create basic macros where one real keypress is used to trigger one or more others. These settings can be grouped in keymaps. By cleverly using these, you can redefine what keys the UHK reports as being pressed and released in which order, but the translation to characters remains on the computer side, so there is a limit on what you can arrange with agent" . Then (maybe) hyperlink into other explanations that go deeper to explain more for people that want/need to know more. 

Another issue with the text could be that it hasn't enough background info to make users realise what a keyboard does and doesn't do/know, as it jumps right into 'scancodes'. Again, here the key point is for the users to understand that the keyboard basically just reports keys pressed/released, and doesn't know/care what's printed on these keys nor what the OS thinks what each key should do (and this is the main reason I got one with blank keycaps myself). The OS keymap links certain characters to certain keys, so you need to choose one that has all the characters you want to be able to type in it, and are then stuck to which ones are paired on the same keys (like 2 and @ on US, but 2 and " on UK), at least until the firmware gets updated to make modifier keys work like layer switches.

Also, it might be helpful (both for everyone's understanding of what's actually going on, as to give powerusers more control) to be able to set and see the actual scancode to be send by each key directly in Agent, instead of identifying it by character/function. This is definately a feature I expect to come in the future, but have so far not mentioned because I thought you guys are too busy right now anyway, and that it is probably an obvious thing that you've already thought of, but shelved for now as an exotic feature, and/or something that can eventually be done via macros or direct editing of saved data.

**Comment by mondalaci** [comment]
@luteijn Thank you for the detailed explanation! I think some of your points are really good, and it'd be worth to include some of them into our guide, or possibly create a simpler guide.

Not sure if it'd truly be useful to display scancodes in Agent. This hasn't asked before. I'd rather wait until we receive more requests.

**Comment by luteijn** [comment]
Usually it is possible to make 'extra' keys (producing unusual scancodes) on a keyboard do something. E.g. under linux: https://wiki.archlinux.org/index.php/Map_scancodes_to_keycodes . If it is possible to make any key send any scancode, the UHK can either emulate a special keyboard, or be used to send something more or less unique and normally unused, that e.g. a macro or other action can be bound to on the OS side. Of course, the UHK's build in macro engine could be used similarly to make, for instance, a certain key 'type' <esc>[Pause] and then handle this in screen with 'bindkey ^[[Pause] suspend'.

**Comment by mondalaci** [comment]
I didn't know about this possibility, but I foresee such methods to be extremely rarely used. Also, I just skimmed through it, but I couldn't see actual USB scancodes listed. These are more likes internal codes.

**Comment by alexthewilde** [comment]
For folks like me, who are still searching for a way to make typing german Umlauts quicker: as @mondalaci pointed out several times, macros are your friend! For instance, to generate `ä`:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/67973/203014039-a7162638-a153-435d-8dc3-8be30d644e16.png">

I assigned this to the `A` key in the Mod layer.

**Comment by taunusflieger** [comment]
> Why wasn't this obvious based on https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk ?
> 
> I try hard to minimize communication overhead by writing guides like the above. Please let me know how I can improve it.

Unfortunately the link doesn't work. Can you please check? Thanks

**Comment by mondalaci** [comment]
Just fixed the page.
