### ISSUE TITLE
mouse speed is too slow (even when maxed out)

### ISSUE THREAD

**Issue by farzher** [UltimateHackingKeyboard/agent#733]
i'm using a custom mouse acceleration driver and like 10,000 DPI. Maybe that's why.

I think i'd be fine if i could just increase the speed a bunch more

maybe just text inputs instead of sliders?

**Comment by farzher** [comment]
this is electron, right? why did you disable opening the dev tools? i could've probably easily hacked in custom values & be good to go

**Comment by luteijn** [comment]
Guessing that it is disabled to protect the innocent. Not familliar with how this works, but would probably be nice to have a little 'enable devtools' button with an appropriate warning in the vein of 'no user-servicable parts inside - qualified technicians only'. For this specific setting it may not help you, as the pointer speed is defined in increments of 25, so 6375 (**255**x25) is probably the highest it can be set to, with the internal firmware variable on the UHK being only a byte. So in order to go quicker, the multiplier should be configurable (or the internal variable should be made wider...)

**Comment by farzher** [comment]
`enable devtools` button is ctrl+shift+i by default. not sure why it's disabled here.
but in this case it looks like you're probably right and i would've been stuck anyway o:

looks like i should just lower my DPI and rescale my mouse driver

**Comment by mondalaci** [comment]
Yes, @luteijn is spot on that the speed is stored in a byte on the firmware level.

So far, the interval has been sufficient for everyone. We might tweak this if we encounter more 10kDPI mouse driver users.

I don't know why debug mode is not enabled in Electron. @ert78gb should know the reason, although I don't think that enabling dev tools would be useful. Certainly not in this case.

**Comment by ert78gb** [comment]
The ctrl+shift+i is not disabled. The Agent does not use menu, and the ctrl+shift+i shortcut is bind to a menu action and not to a function.
