### ISSUE TITLE
Shift+Alt+Meta+Ctrl+\ shortcut doesn't trigger on Mac

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#738]
This is related to ac7d66e338453989629795a51c322466a5fc88b4.

**Comment by ert78gb** [comment]
Has your MacBook Hungarian keyboard layout? If yes u use the `ALT + í` character to type `|`. But `SHIFT + ALT + í` is `Ŕ` character and not `|`.
Mac use different keyboard layout with modifiers. I don't know the exact rules. I use the 'Keyboard Viewer' to see what is the result of the key combinations.

FYI the `ALT + s` also not works on Mac because `ALT + s ` is `ß` charachter.

**Comment by mondalaci** [comment]
Thanks! Looks like Alt changes the character of the relevant key on the US Mac keymap. This should be fixed by https://github.com/UltimateHackingKeyboard/agent/commit/cec891a2c034e37f100766093c42372d26e80cfd
