### ISSUE TITLE
Wrong order of KeyUp events

### ISSUE THREAD

**Issue by miau** [UltimateHackingKeyboard/agent#743]
Mapping:

- Fn key is remapped as Alt-B

Expected behaviour:

- Send Alt-KeyDown B-KeyDown B-KeyUp Alt-KeyUp

Actual behaviour:

- Send Alt-KeyDown B-KeyDown Alt-KeyUp B-KeyUp

**Comment by luteijn** [comment]
To perhaps make this clearer use e.g.: https://w3c.github.io/uievents/tools/key-event-viewer.html and
remap a base layer key to alt-b (or ctrl-c or ctrl-alt-shift-super-d or  whatever), press the key and compare it to pressing the combination by hand... A remapped key seems to use a FIFO/queue instead of LIFO/stack to store the order of keys pressed to release them in the same order they were pressed; intuitively we press e.g. ctrl-alt-delete and release in opposite order del-alt-ctrl. The OS probably also does a little bit of correction here as one might press ctrl-c and release ctrl-c by accident, so it may not be obvious this is wrong, but following the doctrine of being precise in what you send and lenient in what you except, UHK firmware should be doing things 'right'.

As a workaround for cases where this does matter, until this is fixed, one can program a macro to explicitly do a key down for alt, then tap the B key and finally keyup alt, or alternatively 'press B with leftAlt, release B, and release leftAlt'. Then things will work as expected.

**Comment by miau** [comment]
Thanks for the workaround. Works like a charm!

**Comment by mondalaci** [comment]
@miau I think that Alt and B gets pressed in the same report, and released in another report at the same time. How did you measure the "actual" behavior.

**Comment by luteijn** [comment]
Most likely that is what is happening, but that's a very synthetic situation, as in that case it is not clear what the release order is, and a real typist would not release the shifting key before the shifted key (nor press the shifted key before the shifting key).

This is one of the reasons I don't like the way reporting of keyboard status is handled by USB keyboards. They are basically trying to communicate state of the keys, instead of sending just a stream of up-down events that the ps/2 and older interfaces did. On the host side, the sequence of reports is translated back into a stream of up down events that most programs expect, and those then rebuild their own 'state of the keyboard'. So a lot of extra work, and you also lose the ability to hold more than 6 real keys at the same time.

**Comment by mondalaci** [comment]
According to my knowledge, the scancodes and modifiers of keys that have scancodes and associated modifiers get released at the same time. I don't think that the "actual" behavior mentioned is really the actual behavior. I believe that the application used to display this sequence created separate Alt-KeyUp and B-KeyUp events with the same timestamp.

Feel free to reopen this issue, but as a firmware issue.
