### ISSUE TITLE
Repeating key with firmware 8.4.0

### ISSUE THREAD

**Issue by vmauery** [UltimateHackingKeyboard/agent#759]
I was just happily typing along and all of the sudden the keyboard went into a non-stop key repeat of the space key. I had to unplug the keyboard and plug it back in to get it to stop. I just updated to 8.4.0 yesterday and have never seen this problem before. If I see it again, I will update this.
[UserConfiguration-1.2.7-8.4.0.json.txt](https://github.com/UltimateHackingKeyboard/agent/files/2319690/UserConfiguration-1.2.7-8.4.0.json.txt)

**Comment by mondalaci** [comment]
You must have hit the [freeze bug](https://github.com/UltimateHackingKeyboard/firmware/issues/148).

Please join to the discussion there and let us know since how long you're using your UHK and how much time does it takes for the freeze to kick in. (Seems like it takes a day on your UHK). Running the mentioned script when the freeze kicks in would be very helpful.

The only current solution is to downgrade to firmware 8.2.5
