### ISSUE TITLE
Add forward and backward scancodes

### ISSUE THREAD

**Issue by MartinBurian** [UltimateHackingKeyboard/agent#776]
First things first, I just got my UHK and it's awesome!
My laptop, ThinkPad X220, has two media keys I use very frequently, navigation keys next to arrow keys, that are mapped to forward/back in the browser, swithing buffers in emacs etc. They have XF86 keysyms
```
KeyPress event, serial 37, synthetic NO, window 0x4200001,
    root 0x11f, subw 0x0, time 8987486, (0,508), root:(963,530),
    state 0x0, keycode 166 (keysym 0x1008ff26, XF86Back), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
```
KeyPress event, serial 39, synthetic NO, window 0x4200001,
    root 0x11f, subw 0x0, time 9025099, (-2,21), root:(961,43),
    state 0x0, keycode 167 (keysym 0x1008ff27, XF86Forward), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
````
I would love to be able to configure the scancodes into my UHK to remap the Mod-s and Mod-f keys without having to add them to a menu, perhaps just input them manually or have them scanned. Is anything like that planned?

**Comment by mondalaci** [comment]
Thanks for the nice words about your UHK! So glad you like it!

I also happen to have a ThinkPad featuring the same keys, so chances are I'll be able to look up their USB scancodes. Then we'll add them to Agent.

Allowing the addition of custom numeric scancodes is not planned. I think it's a much better idea usability-wise to have Agent contain all the scancodes.

**Comment by luteijn** [comment]
I think there will always be 'one more scancode' that someone comes up with to add; already it seems like quite a big list to scroll through, so for power users (and I'd expect quite a large percentage of users to be a power user, otherwise why bother with this kind of keyboard) a way to send arbitrary codes would probably be welcome. Might be something to unlock via the macro functionality?

**Comment by mondalaci** [comment]
I strongly disagree regarding arbitrary scancodes. If this was really a big problem, users would often ask us to add scancodes, but it happens extremely rarely. The size of the scancode select2 list is manageable and shouldn't be an issue due to its incremental search feature. The current solution is intuitive and doesn't allow for user errors. I'm confident that not allowing arbitrary scancodes is the best way forward.
