### ISSUE TITLE
Alternative privilege escalation on Linux

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#781]
Currently, Agent uses PolicyKit on Linux to escalate privileges, set up the udev rules and restart the udev daemon to access USB on the first run, but one some distros (Arch included) polkit is not installed or it's not working by default. In such a case users have to manually run commands which negatively impacts user experience, so an alternative way is needed to escalate privileges on Linux.

See:
* [Video from Riscy business](https://youtu.be/VoBgLJGRKiM?t=2m27s)
* [Video from David Udelson](https://youtu.be/hdiU9H7YC0Y?t=30m40s)

What should we use? Possibly gksu?

Whatever we use, it should be present on every Linux distros.

Suggestions are welcome!

**Comment by kareltucek** [comment]
Well, using a distro which intentionally forces the user to use terminal for its administration as an example is pretty hilarious ;-). 

My humble opinion regarding user experience: users with non-mainstream systems usually don't mind having to setup privileges manually via a few simple commands as longs as they don't have to spend hours figuring out which these commands are. It might be even preferred to having to give root privileges to "some random app". So my suggestion is: do not over-engineer it. Just provide clear information regarding what the agent needs from the user. 

(Please keep in mind that the user might not have superuser privileges at all. The knowledge what the agent actually needs is vital in order to get help from the actual administrator.)

**Comment by mondalaci** [comment]
@kareltucek Gotcha, but I still firmly believe that Agent should work out of the box as much as possible, and not make the user think or make him do any extra action unless absolutely necessary, so I'm still interested about a solution.

**Comment by mondalaci** [comment]
Thanks for the detailed writeup. Appreciate it very much! 

I agree that spawning terminals is out of question. I assume that kdesu isn't installed by default on Arch either, right? If so, that leaves us no options, I believe.

You're saying that kdesu or gksu might not work on Wayland. How many percentage of users use Wayland?

**Comment by kareltucek** [comment]
>  I assume that kdesu isn't installed by default on Arch either, right?

Right. 

> How many percentage of users use Wayland?

Honestly I don't know. I assume that at the moment it's very small minority. However, here are two things to take into account:

- Gksu does not work on Arch because Arch seems to follow the same conceptual security reasoning as Wayland (just applied on XOrg). Kdesu should still work on Arch, but that is because it uses polkit too, so it doesn't really solve anything on this front.

- Second: XOrg is said to be obsolete for 20 years by now, so ignoring its possible successors is probably not conceptually very wise thing to do.

Personally I do not want to discourage you from using gksu, because that seems as a reasonable default to me and chances are that other non-mainstream distro's won't suffer these constraints. 

Also, note that I am no expert in this field.

**Comment by mondalaci** [comment]
Based on what you wrote, and based on the reply of [Riscy Business](https://twitter.com/hmn_riscy/status/1041469537844113410) and [David](https://twitter.com/dudelson_/status/1041458319804833792) (see videos in the top comment) we can't rely on kdesu and gksu.

According to the videos, people are prone to mess things up or overcomplicate the process, so I'll make the text instructions more straightforward as follows:

1. Open a terminal.
2. Run `su` to become root.
3. Paste the following script:

**Comment by kareltucek** [comment]
Sounds good!

**Comment by mondalaci** [comment]
The updated screen:

![untitled](https://user-images.githubusercontent.com/300402/45851096-5e703e80-bd39-11e8-8213-eb036c3c2dba.png)
