### ISSUE TITLE
Missing "SysRq" Key / Functionality

### ISSUE THREAD

**Issue by davidpgil** [UltimateHackingKeyboard/agent#784]
Please add this functionality. It could us Linux users prevent a corrupted OS.

Some background info:
https://en.wikipedia.org/wiki/Magic_SysRq_key
https://www.youtube.com/watch?v=ZF2kOk0al7E

**Comment by luteijn** [comment]
Should be alt-printscreen, like break is ctrl-pause. Agent doesn't actually seem to capture pressing the printscreen/sysrq key properly, likely because it is supposed to send a slightly wonky scancode sequence, but you can select print screen from the dropdown, and combine it with left alt to create a sysrq key. If you map it to a layer, make sure that layer also has the keys you want to press together with the sysrq key available, or you'll only be halfway to paradise...  

Might want to use the macro functionality to make a couple of macros instead, that simulate press-hold of alt, print screen and then tap of e.g. space or one of the other command keys and then, release of print screen and alt. Alternatively, could make a special SysRq keymap to switch over to that has the command keys and sysreq available easily.

**Comment by davidpgil** [comment]
I think the key is still worth adding "officially" though. I find the idea of making a keymap for this very interesting! Good idea!

**Comment by kareltucek** [comment]
https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html#dellnoup

If I understand the link correctly correctly, then SysRq indeed has it's own scancode, which is however triggered via alt+PrtScr on most keyboard.

**Comment by luteijn** [comment]
As SysRq is basically used as a modifier key in this case, it might be good to have it added as an option in the list of valid 'secondary' keys, so one could bind it to e.g. the Esc, Backspace or ~ key as a secondary role.

**Comment by davidpgil** [comment]
I like the idea of mapping it to the escape key because it has more to do withe "escaping" than printing the screen. :)

**Comment by luteijn** [comment]
Basically this also comes back to decoupling scancodes from the 'usual' keys they are on, and make it easier to have certain chords send out whatever scancode (sequence) one wants.
 
Planning to do this kind of decoupling is exactly why I got a blank keycaps version of the board, and the iso version, to have at least one more key to play with. Ideally there'd be a few more keys on the left half, an extra column would have been nice, so there could be dedicated keys for Esc, ~ and some macros.

**Comment by mondalaci** [comment]
SysRq = Alt + Print Screen

They share the same scancode, so they're displayed together from this point forward.

**Comment by kareltucek** [comment]
Yes, I tested it and it works. See the stackexchange in order to determine which functions are enabled on your system.

Also don't forget that default UHK has PrtScr in the Fn layer, which does not have letters bound, so you effectively cannot issue the commands with default UHK keymap.

**Comment by davidpgil** [comment]
My UHK came with "PrtScr" on the "Mod" layer, however, you definitely are correct about the letters missing from the layer. I feel a bit silly now. Thanks!

**Comment by luteijn** [comment]
:)  I tested it yesterday and ran into the same issue when planning what to test, which is why I added the "If you map it to a layer, make sure that layer also has the keys you want to press together with the sysrq key available, or you'll only be halfway to paradise..."-remark that was probably snowed under with all the other comments. 

As I was testing out how agent reacted to trying to capture printscreen + modifiers earlier, I'd already reserved a few test keys in the Fn layer and just added a 'space' key next to it so I could just press Fn and two keys next to each other. That's how I came up with the might want to 'dedicate a keymap to this'-idea. Maybe the future expensive version of the uhk will have keys that change their caps to match the current layer/map selected. 

Anyone else trying this out in the future:
Space is probably the best key to test things with as it won't do anything more destructive than outputing some text in a console window. Make sure to actually switch to a virtual console with e.g. ctrl-alt-F1 (ctrl-alt-mod-1 on uhk), and maybe try with a generic keyboard first to check if it works at all.

**Comment by davidpgil** [comment]
@luteijn Thanks for the clarification on that. I was basically in the mode of geeking out on what ELSE can I do with my UHK, and that lead me to the rabbit hole of the more esoteric keys on a full keyboard. I JUST heard about the SysReq key a few days before I opened the issue due to following a forum where somebody really correupted their Linux system by doing a hard reset.

Sorry I missed the actually well stated details about this key. I JUST got it working with a special keymap that isolates some of the main functionality of SysReq, along with a macro that does the "reisub" combination that I mapped to the corner "Esc" key. I love how it works! Thanks so much!
