### ISSUE TITLE
Allow Middle Click While Holding Left and Right Mouse Butttons

### ISSUE THREAD

**Issue by davidpgil** [UltimateHackingKeyboard/agent#795]
I'm using my UHK edge/body buttons as mouse clickers. Since there are only two of these buttons, I propose allowing holding mouse buttons to create a middle click. Thoughts?

**Comment by mondalaci** [comment]
Sorry, but I don't plan to support this, because this is quite a special feature, and nobody has requested it.

There's an option in Linux to do this natively. I'm not sure about other OSes.

**Comment by kareltucek** [comment]
Obviously, this cannot (i.e., should not) be implemented globally.

Regarding speciality of this feature... functionally this corresponds to the many times requested arbitrary-chord-to-action feature, which is an idea which has my full support. Unfortunately, it is not planned (yet?) for "being too complex to implement", "being too difficult to understand by users", "cluttering UI too much" or "lack of user interest" reasons as far as I dare to guess. 

For the time being, you might be able to "fake" this via secondary roles - set the right button's secondary role to switch to a different layer, and have the left case button mapped to middle click on that layer. This will however have consequences:
- the sequence will have to be right click and then left click (not vice versa)
- right click will trigger on release instead of press
- you will loose ability to drag&drop with right button 
- it works from base layer only (actually it should work on non-default layers too on older agent&firmware due to a "bug")

You can do the same symmetrically, but then you will loose drag&drop on left button too, which I assume is not desired.

**Comment by davidpgil** [comment]
After doing a bit more investigation, there seems to be little need for the middle click aside from the scroll wheel. So, I am actually OK if I don't have this feature. I mostly just wanted to see if you had an opinion in this... Also, it does seem this can be solved natively in different ways on the various OSes.

**Comment by kareltucek** [comment]
@#$_&-+()! Totally forgotten about that.
