### ISSUE TITLE
Remove USB usage messages

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#824]
Since we updated to the latest node-hid, a lot of USB usage related messages get dumped into the console. These should be removed.

```
dev 28de / 1142 : usage_page:2bc0, usage:ffc5
dev 28de / 1142 : usage_page:33, usage:7c4
dev 28de / 1142 : usage_page:33, usage:3f80
dev 28de / 1142 : usage_page:33, usage:4207
dev 28de / 1142 : usage_page:33, usage:0
dev 46d / c332 : usage_page:33, usage:0
dev 46d / c332 : usage_page:30, usage:2d32
dev 1d50 / 6122 : usage_page:2100, usage:ffc1
dev 1d50 / 6122 : usage_page:6279, usage:616f
dev 1d50 / 6122 : usage_page:6279, usage:616f
dev 1d50 / 6122 : usage_page:6279, usage:616f
dev 1d50 / 6122 : usage_page:6279, usage:616f
dev 28de / 1142 : usage_page:a960, usage:ffe5
dev 28de / 1142 : usage_page:33, usage:2f65
dev 28de / 1142 : usage_page:33, usage:0
dev 28de / 1142 : usage_page:33, usage:ffed
dev 28de / 1142 : usage_page:33, usage:0
dev 46d / c332 : usage_page:33, usage:ffdb
dev 46d / c332 : usage_page:30, usage:2d32
...
```

See https://github.com/LedgerHQ/ledgerjs/issues/204 which is probably the right fix.

**Comment by TorC8** [comment]
When I just updated to git head a few minutes ago I got those messages, and further, Agent couldn't find my UHK... which I was actively using at the time.  I'm inclined to thing it's an agent issue because I was using Agent just prior to updating without issue.

My git log of the agent update:
b5cff2fa9371e17fb5e1c1409dff83b22bc38b1c e3330220439c380fe183ddf8dd95a7f751695030 Tor Chantara <user@redactedhost> 1539166906 -1000 pull: Fast-forward

**Comment by mondalaci** [comment]
@TorC8 I assume you use Linux. If so, update the udev file, restart udev, and reconnect your UHK. Let me know how this fix works for you.

**Comment by ert78gb** [comment]
This issue blocked by node-hid/node-hid#277
