### ISSUE TITLE
Fix npm vulnerabilities

### ISSUE THREAD

**Issue by xellio** [UltimateHackingKeyboard/agent#825]
Running `npm install` after cloning the agent will result in a warning like

> audited 43340 packages in 9.53s
found 46 vulnerabilities (34 low, 1 moderate, 11 high)

At least, fixing those high vulnerabilities is not that hard.
Running the `npm audit fix` command will fix most of those vulnerabilities.
I will create a PR for this one.

**Comment by xellio** [comment]
Not fixing known and obvious (in terms of presentation - by npm) vulnerabilities is reckless not a good idea - even if there is no bandwith for tasks like this. This should have a higher priority than any new feature.

For me - as a non javascript dev - it took less than an hour fixing this problem.
Those 11 high rated, as well as the 34 low rated vulnerabilities are gone.
The single moderate one is still present due to possible breaking changes.

I can not understand that this issue is closed without any comment (except the one on my first pull-request, that there is no bandwith for tasks like this). There is no bandwith for obvious security problems?

I know that you have a lot work to do - but you decided to create a javascript application with all its advantages and disadvantages. If you are not able to handle external dependency updates (due to existing workload), maybe you should rethink this decision.

Does it make sense to have green tests but known vulnerabilities in my code? Do you really want to ship known vulnerabilities to your customers? Don't get me wrong - I have a lot of respect in what you are doing. But closing a reasonable ticket without a comment is not the best way to handle feedback from possible contributors.

**Comment by mondalaci** [comment]
Upgrading npm packages is not always trivial. Sometimes they require a significant time investment with testing included. As long as we have a single part time developer working on Agent, we will not jump on (the very frequent) security notifications of npm, but rather address them in batches from time to time. I respect your opinion, and don't expect you to agree.

Sorry for closing this issue prematurely. I didn't expect that you actually followed up with a fix. Thank you very much for your contribution!

**Comment by ert78gb** [comment]
Hi @xellio you wrote you are not a javascript developer and I think this is the reason why you are worried about the vulnerabilities. We don't like them too :)

We always try to keep the dependencies up-to-date, but the Agent is a moderately complex application. It is a real multi-platform app, I mean it is not just a web app. The Electron gives a shell and the web app is able to run on the desktop.
The following areas are totally OS dependent and we have to be very careful when making changes:
- installer package (electron-builder dependency)
- usb communication (node-hid)
- electron
Every time we change one of the components above we have to fully test the app on all platforms i.e. what happens on the first installation, what happens when the app is updating etc. It is a long process.

Before I upgrade any components I read the release notes what has changed between the currently used and the latest version of the dependency package.

I would like to assure you that the built version of Agent does not contain more vulnerabilities than any other software that you download from the internet. 
The development "environment/packages" contains vulnerabilities, but these codes do not deploy to the user computer. If you look for what kind of vulnerabilities the developer dependencies contains, you will see these are not harmful in case of Agent or the development. 
Agent has not got any listeners to the internet so any of DoS attacks are not an option.
Mainly the keyboard and the computer owner use Agent. I suppose nobody likes spending his/her free time to negatively hack Agent, which makes him upset. On the contrary, I hope positive hacking makes them much happier.

If you think there are some real vulnerabilities in Agent pls report it. I, and I think Laszló as well is fully open to review, investigate and fix it. 

P.S.:I will review your PR and I will write the PR relevant comments there.
