### ISSUE TITLE
Key text is overlapping 

### ISSUE THREAD

**Issue by NejcZdovc** [UltimateHackingKeyboard/agent#83]
If you select scan code on small key that is meant for long key, text is overlapping.

![image](https://cloud.githubusercontent.com/assets/9574457/18025571/e6cc3752-6c2d-11e6-976c-ade22c48b649.png)

**Comment by mondalaci** [comment]
Good catch Nejc! I could foresee this happening.

There are multiple strategies to deal with this. The first that comes to my mind is to break the words into several lines. On second thought however that may be unintuitive because just as in the case of the top row the user may think that the first line is produced when shifting the key and the second when not shifting it.

Alternatively, we could shrink the size of the whole text to make it fit within the key. This would result in a wide variety of text sizes, some of them very small so it doesn't feel like the right thing to do.

My third idea is to simply chop off the end of the label and put "..." to the end. The width of the text could be queried via its bounding box. How about implementing this one?

**Comment by laxu** [comment]
We would need several of the options here to make it look right or alternatively abbreviate long key names when trying to map them to 1u keys. For example Caps Lock could become "CL". 

I think the way they are done for the mouse keys would work as those fit quite a bit of info into a 1u space, I suppose that is the 2 line option.

**Comment by mondalaci** [comment]
I would probably rather replace key names with icons wherever possible if space is tight. There are icons for keys such as such as Caps Lock or Shift. If no relevant icon exist then abbreviation is an option.

Maybe it'd be useful to list all the key names that don't fit well on 1U keys starting from the longest to the shortest and address each case.

**Comment by laxu** [comment]
Key names that do not fit in 1u space:

- Backspace
- Scroll Lock
- Caps Lock
- Num Lock

Abbreviating those will fix this easily.

Macros also do not fit as pretty much every macro will have a descriptive name. Maybe implement automatic numbering for Macros or truncate their names as a separate issue?

**Comment by mondalaci** [comment]
The mentioned 4 keys seem to be affected, indeed. Given that easily recognizable icons exist for Backspace and Caps Lock, I'd much prefer to use icons for them. As for Scroll Lock and Num Lock, their typical abbreviations that I found are ScrLk and NumLk which would make sense for us, too. These abbreviated alternatives should be easily recognizable, so for the sake of simplicity, I think we should always display them regardless of the available key space.

Regarding macros, I'd much rather just display their first couple characters, postfixed with "...". That would still be more informative then displaying a mere number. I don't think that a separate issue is justified for macros.

**Comment by mondalaci** [comment]
@ert78gb When you get to this issue the following needs to be done:

First of all, `npm build sprite` needs to be fixed because it doesn't generate a correct sprite.

Then `mapper.service.ts` will have to use `kbd__backspace.svg` and and `kbd__caps-lock.svg`.
