### ISSUE TITLE
Select2 UI improvements

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#84]
On the Keypress tab of the key action editor:
- the text should be left-aligned
- "Functionkeys" should be written as two separate words
- alternative names like PgDn pagedown should be right-aligned and displayed with gray color

On the Layer tab of the key action editor:
- the filter input should be removed because there are only 2 or 3 options

In general:
- the height of select2 dropdowns should occopy all the available vertical space.

**Comment by NejcZdovc** [comment]
@mondalaci I am not sure what this means:

> the height of select2 dropdowns should occopy all the available vertical space.

Can you explain a little bit please?

**Comment by mondalaci** [comment]
Sure thing!

![ultimate hacking keyboard configurator](https://cloud.githubusercontent.com/assets/300402/18067993/982b64d8-6e3f-11e6-9ba7-d161b7dac076.png)

As you can see right now selects have a fixed maximum height instead of stretching till the bottom of the screen. It'd be nice to use all the available screen space.

**Comment by NejcZdovc** [comment]
Ok, got it. This is not a straight forward thing. To achieve this we would need to add additional JS logic to it, because this can't be controlled with CSS. The problem is that drop down can be in multiple places (not only in popover) and that's why CSS can't help us. We would also need to add listener to resize event, because if user resizes window and drop down is opened we need to resize drop down accordingly.

I don't really think that this is a problem. You have search input which helps you navigate. One thing we can do is that we increase height from 200px to for example 300px.

![image](https://cloud.githubusercontent.com/assets/9574457/18077520/8a3e4dbc-6e86-11e6-8da7-af3cc25927e4.png)

**Comment by mondalaci** [comment]
Thanks for the explanation! I wouldn't have thought that this is so hard to achieve. 300px sounds like a good default.
