### ISSUE TITLE
Add More Common Media Keys

### ISSUE THREAD

**Issue by skaldesh** [UltimateHackingKeyboard/agent#852]
Hey! I am loving my UHK so far!
Is it possible that more common media keys are configurable in the agent?
I am talking about:
- XF86MonBrightnessUp
- XF86MonBrightnessDown
- XF86AudioMicMute
- XF86AudioMicRaiseVolume (dont know if it exists)
- XF86AudioMicLowerVolume (donk know if it exists)
- XF86Bluetooth
- XF86WLAN
- maybe more?

**Comment by mondalaci** [comment]
Glad you're loving your UHK!

I'm not sure which of these X keycodes have related USB scancodes. You're welcome to research them. The ones that have are likely featured in the Consumer Page section (starts at page 75) of the [USB HID usage tables](https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf) document.

Another important criteria is OS support. We will only include those scancodes that are supported by all 3 major OSes, otherwise we'd keep getting reports from people, saying that they don't work on some OSes.

**Comment by kareltucek** [comment]
> Another important criteria is OS support. We will only include those scancodes that are supported by all 3 major OSes, otherwise we'd keep getting reports from people, saying that they don't work on some OSes.

I'm very sorry, but this is bullshit. Your keyboard is supposed to send scancodes. Caring about how the host OS interprets them is non of your business. If an OS does "not support"* a scancode, you simply don't bind it in the preconfigured OS-dependent keymaps.  

*What the hell does this even mean? Does it mean that an OS does not support such action, or does it mean that its window manager does not have it bound?

**Comment by luteijn** [comment]
Some form official support (even if it's just in the form of a generic 'enter hex value to send' combined with a "here be dragons" message that people using it are on their own) for being able to send arbitrary scancodes to bind some function to at a higher level is something I will keep wishing for...

**Comment by skaldesh** [comment]
Indeed, arbitrary scancodes would be really cool! I think the volume lower and raise media keys do not exist. Then I could create them myself.

**Comment by mondalaci** [comment]
Volume Up and Volume Down exist.

**Comment by skaldesh** [comment]
Sorry, was talking about the 
- XF86AudioMicRaiseVolume (dont know if it exists)
- XF86AudioMicLowerVolume (donk know if it exists)

So, I looked through this Consumer Page you linked above, but I could not find these codes.  
However, would it be possible to add them anyways? I am a real newbie in all this stuff and I just thought that I'd like to control everything with my UHK. So in my mind, it is possible that the UHK simply sends out the exact same key code that all laptops emit when I press these buttons. 

Or, if that varies between manufactures and there is no standard, then @luteijn suggestion would be nice, that I just configure them myself in the agent

**Comment by mondalaci** [comment]
This is not the first conversation of its kind, and my opinion is unchanged: I don't support custom scancodes for the same reason I don't want to get non-cross-platform scancodes included: They increase support requests and complexity while not providing substantial value for most.

Some of the laptop shortcuts are not available in the form of USB scancodes, and I don't know the USB scancodes of the mentioned XFree codes. We won't allocate resources for this issue, but you're free to experiment, and send us a PR. Only cross-platform scancodes will be merged.

**Comment by luteijn** [comment]
I don't think there is a standard code for many of these X actions that are available for binding to any key/chord you want, it is just a question of any key that exists 'cross-platform' in the first place being most likely something you don't want to want to give up as it probably does something you want to keep. 
The non-standard scancodes come in when you want to assign such an applucation/os/system specific action like e.g. 'focus on next window', 'invert all colors', 'tile windows', 'switch between 80 and 132 columns', or 'switch to next lower resolution' to anything easy, instead of a fingerbender like 'alt-altgr-ctrl-shift-super-esc' AND keep all the cross-platdorm standard keys as is.
Compareable to dedicated macro-keys on some keyboards - which is why I wouldn't mind if this 'send system specific scan-code' option was hidden in the macro-engine instead of being on the main drop down of assignable key codes.

**Comment by laxu** [comment]
At most we could have arbitrary keycode support like suggested, I've found this useful with some QMK builder GUIs that don't support every keycode supported by QMK. Input keycode and it either works or doesn't. There's a ton of proprietary keys supported by laptops etc but I am not sure how their handling is typically implemented (driver, laptop firmware or sending custom keycodes).

To me it should not be part of the macro engine but just an extra option available in the keycode selector. Then it could be used on both layers and inside macros.

**Comment by skaldesh** [comment]
@mondalaci I think I read in an old issue already that you are not happy with providing this feature of sending custom scancodes. But I think your community and customers would really like this feature. After all, you call your keyboard the "Ultimate Hacking Keyboard", not the "Ultimate Consumer Keyboard".  

You say that "They increase support requests and complexity while not providing substantial value for most."  
That support requests increase might or might not be the case, I dont think you can reliable tell this at the moment. To help preventing them, the agent could show a warning (like it does when one changes a modifier) that sending custom scancodes is something for advanced users etc.  
Increasing the complexity? I dont know the code base, so maybe I am, again, thinking too easy, but isnt it just sending the configured scancode, instead of one of the predefined ones? And nothing else? If you mean complexity for the consumer, why though? I dont see the complexity in it either.  
Last but not least: "not providing substantial value for most". That this feature is not for the majority of users is certainly true! However, your keyboard already targets a niche in the keyboard consumer world, mainly enthusiasts. I think the amount of people benefiting of this feature could be higher than you expect.

**Comment by mondalaci** [comment]
@skaldesh Ultimate Consumer Keyboard is a wild exaggeration even given our current feature set, but I can see your point.

I've managed to come up with an implementation that allows for custom scancodes, yet it won't confuse regular users. I'm closing this issue in favor of the newly opened #857.

May the UHK be with you.
