### ISSUE TITLE
Macro text playback must consider OS keymap

### ISSUE THREAD

**Issue by piratk** [UltimateHackingKeyboard/agent#870]
I tested the macro key playback from the latest agent and firmware release (1.2.12/8.5.3) and sadly, the old "display the correct character" problem bites again, I wanted to go to the ultimate hacking keyboard site, but the url entered ended up as:

> httpsö--ultimatehackingkeyboard.com/

This is not surprising, as I am using Swedish keyboard layout, and the physical location where : is in US English keyboard layout is the same as where ö is on a Swedish keyboard, hence, we get httpsö instead of https:, and so on. 

Of course, I can reprogram the macro to make use of keyboard grabs instead of text playback, but as it is right now, text playback can only work with US English, and I suspect it can't work independently between mac and windows.

This gets worse, on German keyboards, Z and Y have swapped positions relative to US English for instance. 

I have no obvious solution for this, but text playback should be used with caution.

**Comment by kareltucek** [comment]
There's no way for UHK itself to know your software layout. Of course, agent could probably retrieve layout information and "transcode" it into scancodes on its side before serialization, but that's not how it's currently implemented. Still, retrieving such information in platform-independent manner is very non-trivial problem and such solution would not be station-independent...

Regarding available solutions:
- The obvious solution to add a key shortcut which switches your system to EN layout the macro is playing (i.e., switch forth at the beginning of the macro and back at the end).
- Another solution might be to use the runtime-macro recorder which is available on my fork of the firmware (sadly, it doesn't store these macros into persistent memory and does not interface them to the agent). Then, the macro will work on scancode level - simply replaying what you have written on the keyboard while recording the macro.

**Comment by mondalaci** [comment]
Karel is spot on. Read the "Accented characters in Agent" section of https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk to see why it's so incredibly problematic and won't be implemented.

**Comment by mondalaci** [comment]
I closed this issue because as I clearly explained above I don't think it's worth the effort. It's not just the type text feature, but scancodes in general.

**Comment by luteijn** [comment]
I see the 'type text' feature where a string of text is translated to scancodes to send as really a convenience bonus feature - it is a nice to have that the keyboard can do it at all, instead of relying on a component higher up in the stack, e.g. agent, or a 3rd party utility like autohotkey that is more aware of the OS to do conversion of key(-chord) entered and text to be put. With the ability of the keyboard to just send a unique scancode for keys intended to do 'something else', it is not needed to do all the processing on-board, as this makes it a lot easier to add this layer of functionality externally, without interfering with OS-defined shortcuts...

**Comment by thorhj** [comment]
@mondalaci Would it be a possibility for the user to define the OS mapping manually inside Agent such that the Agent used that mapping to translate just the UI (i.e. macro recording would not be affected, but the displayed text would be translated according to the defined OS mapping)? I must agree that without this feature, the Agent is hard to use on a different OS mapping than US.

This would also be relevant for the symbols shown on the keymapping screen.

**Comment by mondalaci** [comment]
@thorhj It's possible, but it'd be a ton of work.

**Comment by kareltucek** [comment]
@mondalaci, isn't this basically about having an array containing a map from scancodes to characters somewhere and injecting translation via this array at like three places in the code? As long as there's a way how to specify this array (one textbox or a configuration file), it doesn't sound very difficult. 

I see that it's not a top priority issue, but if you stated "We want it as long as somebody else implements it.", somebody might actually do so...

**Comment by mondalaci** [comment]
@kareltucek This is significantly more complex than it appears at the first sight because modifiers such as AltGr (right Alt) heavily affect characters in a number of layouts.

If this ever gets implemented, an already existing database of layouts must be used instead of adding languages one by one manually, as the latter would be very laborous. Linux distributions surely contain such a database.

Lastly, I'm unsure whether this mapping should be global or keymap-specific. In any case, ideally, this information should be saved to the UHK configuration, so this would require modifying the binary user configuration and trasforming the previous configuration format to the new format for which a significant groundwork would have to be done in Agent.

**Comment by kareltucek** [comment]
Well, yeah, I do see that implementing this in a complete and all-encompassing variant is next to impossible, but that's now what I or thorhj are suggesting. I am suggesting just a totally minimalistic UI translation which would simply serve the user to define his own captions-per-scancode so that he does not have to define his keymaps with a ciphering table in hand (e.g., in case he has never seen a US layout in his life)...

AltGr does not have to be taken into account at all as long as we don't want the Agent/firmware to automatically transcode characters in a shift/altGr independent manner. (Yes, not considering them rules out transcoding text actions, but that itself is an edge case which I believe is not used by many.) 

There's no point in having to provide a big database either - specifying such map by hand can be as easy as swiping across keyboard with hand line by line (if special characters are avoided). Similarly, there's no need to store this on keyboard or make it per-keymap if it is a problem.

I can see that being so minimalistic is strongly against your philosophy, on the other hand not giving users any option is not very user friendly either.

**Comment by piratk** [comment]
Wouldn't it be possible for the agent and in conjunction with the UHK to test each scan code and see what happens? Sure, some codes are modifiers, and some are multi key press for character... But with some logic, it would be possible to test most of the mappings?

**Comment by mondalaci** [comment]
@kareltucek The way I see it, using an already existing database is the only viable way to implement this. Alternatively, this'd end up being a neverending mainteance burden as there would always be new layouts to be added.

Now that I think about it, properly implementing macro text translation is pretty much next to impossible given the range of characters featured on the modifier layers of OS layouts, so AltGr feels overkill, indeed.

@piratk Your suggested solution has already been suggested by a customer, and it would work to some degree, but emitting scancodes can interfere with the OS / window manager / applications that gain focus during the procedure. I'd much prefer providing a wide range of OS layouts that can simply be picked from a select2 input. This would result in the best user experience.

Thinking further about this, I believe that the selected OS keymap shouldn't be stored on the UHK. Agent should simply act as a frontend in this manner, and the OS layout option would be global Agent setting. The firmware wouldn't have any knowledge of it, as it fundamentally works with scancodes, not with characters.
