### ISSUE TITLE
Make USB scripts work

### ISSUE THREAD

**Issue by llinfeng** [UltimateHackingKeyboard/agent#891]
I enjoy UHK sooooo much that I ordered my second pair right when I received the first one, and now I have two of them. Yet, it is a bit of trouble to "sync" the settings on these two.

For now, I have been happily pressing my mouses in the GUI of the UHK Agent, and have only done so for one. Yet, for an indefinite time to come in the future that I shall be happily typing on UHK, I'd like to press a button on UHK to **save-to** or **source-from** the `UHK_master.json` file that I keep in Dropbox.

Please advise if the feature has been in place. Then, how can I call the Agent from the command line, and what flag should I use to specify the action + whereabouts of the source json file?

**Comment by llinfeng** [comment]
I use Windows 10 most of the time, but I think it is also appropriate to ask for support on other OS.

**Comment by owlstead** [comment]
This kind of behavior has been discussed before. Currently there is limited amount of copying possible between key maps and such things. I'm currently writing other software, but handling JSON files is not that hard, so you might want to try yourself - if you're into programming.

**Comment by mondalaci** [comment]
Thank you very much for your big support, @llinfeng!

We'll eventually implement a cloud sync feature, but it'll take quite a while, and it won't utilize Dropbox. In the meantime, we have a couple of useful scripts in ${agentDir}/packages/usb, but they're not actively maintained, and the relevant `read-config.js` and `write-user-config.js` scripts don't seem to be working. We'll fix them eventually, but they're not a priority right now.

**Comment by luteijn** [comment]
As I now also have two keyboards, I'll probably look into this a bit more myself (eventually...) and will at least keep track with interest of what progress is made on this front.

**Comment by Dagon** [comment]
I'm in the same boat - ordered a second for work about a week after I got my first one for home.  I don't update keymaps very often - a bunch when first setting up for a new environment/layer and now maybe once every few weeks.  So far, it's worked to use Configuration->Export on whatever machine I've just made a change, and then Import on the other (I just rsync a directory of random window and app config files rather than dropbox, but same idea).  

I've got some really hacky python scripts to try to do partial-layer-copies on an export file.  This works, but is kind of ugly and requires hacking whenever I want to change which keys are shared between which layers.

I'd enjoy the ability to automate this, but it might be part of a bigger and more interesting agent feature:  agent scripting.  If I could write a file of commands/clicks for Agent to execute, and run that from the commandline, I could script anything, from simple key changes to fairly complicated copy-and-edit of layers.

**Comment by kareltucek** [comment]
@dagon, I am afraid that we won't get any advanced features for the Agent anytime soon. Yet, regarding the possibility of dynamic construction of layers/keymaps, I see quite some potential in firmware hacking. If you are interested, please check the https://github.com/kareltucek/firmware repository and https://github.com/kareltucek/firmware/issues/2 and let me know what you think about it. (Currently, the firmware allows having "hold" layer switches pointing to layers of different keymaps.)

**Comment by mondalaci** [comment]
The fix for this issue should also address #429, so I'm closing the latter.

**Comment by mondalaci** [comment]
#1345 just added `packages/usb/{read-config,write-user.config}.ts` which allow synching UHK configurations programmatically.
