### ISSUE TITLE
Allow user user defined custom text on each key in keymap view

### ISSUE THREAD

**Issue by redwards510** [UltimateHackingKeyboard/agent#912]
It's hard to remember all the fancy key bindings we make using Agent. I request the ability to label each key in the keymap with whatever text you want, so it's easy to remember what exactly that key does. This is purely a visual enhancement. Where it gets really useful is for those of us that take a screenshot of each layer in Agent and print it out so we can more easily remember what key does what.

**Comment by jfieber** [comment]
As a somewhat clumsy workaround, I've taken to making macros, even for a single key+mods action, just so I can label them meaningfully.  Updating the config format to accommodate user labels would be fabulous.

**Comment by kareltucek** [comment]
I think that macros are actually the good way to do this, because they let you create the label/macro once and then use it on all desired layers/keys/keymaps. I think that binding complex keys manually on multiple places and labeling them on all the places would be more tedious than the macro approach.

**Comment by mondalaci** [comment]
I also suggest the macro approach.

I'm sorry, but I'm closing this issue, because it'd take too much effort to implement and maintain it compared to the value it provides for most.

Feel free to continue the discussion regardless.
