### ISSUE TITLE
issue between toggle and key

### ISSUE THREAD

**Issue by sribst** [UltimateHackingKeyboard/agent#949]
Here is the mapping that brought an issue 
key 1 : activate mouse no toggle
key 2 : toggle mod layer AND middle click on mouse layer

when I press key 1 then key 2 it toggle mod layer instead of middle click

**Comment by mondalaci** [comment]
You can't activate two layers at the same time. You must deactivate (release) the mouse layer to activate the mod layer. This use case is not planned to be supported. Please see this UHK firmware fork which may allow what you want: https://github.com/kareltucek/firmware

**Comment by sribst** [comment]
I might have wrongly explain, 
I don't want to activate two layer at the same time

the "roadmap" I want to be able to do ;
- base layer -> hold KEY 1 -> mouse layer -> press KEY 2 -> middle click 
or
- base layer ->press KEY 2 -> toggle mod layer

**Comment by mondalaci** [comment]
Both of these are supported by Agent.

For the first, go the the mouse layer, and click on the middle click key to see how it's configured.

For the second, click on the Mod key to see how it's configured. You can see a toggle option.

**Comment by sribst** [comment]
Yes it's exactly the mapping I currently have on agent but when I hold KEY 1 then press KEY 2 it toggle the mod layer where it should emulate the middle click

**Comment by mondalaci** [comment]
As I said before, you can't activate two layers at the same time. You have to release the mod layer first. Only then can you activate the mouse layer.

**Comment by kareltucek** [comment]
@sribst please attach your userconfig and tell us which firmware version you are using.

**Comment by sribst** [comment]
I'm using firmware 8.5.3
[UHKconfig.zip](https://github.com/UltimateHackingKeyboard/agent/files/3186858/UHKconfig.zip)

 Here is my config
Thanks

**Comment by kareltucek** [comment]
I can reproduce the problem with both 8.5.3. and 8.5.4.. The culprit is apparently the devilish algorithm in `layer.c` and its order of evaluation. Also, it *might* be indirectly related to UltimateHackingKeyboard/firmware#199.

In any case, this is a bug. (And it is firmware bug, not agent bug.)

@mondalaci I would recommend reading the report again while noting that sribst is gracefully ignoring 3rd persons 's' suffixes when reporting how his UHK actually behave**s**. Long story short, the keyboard performs *base layer* action when it should perform *mouse layer* action.

Regarding solution. There are currently three different layer switching mechanisms in the official firmware (namely "Toggle", "Held" and "Secondary"). And they interfere in hardly predictable ways - there's been plenty problems with them in the past and I dare to say that this isn't the last we hear about them. I think that it might be a good idea to replace the three mechanisms by a single stack-based solution which would respect the abstraction-level of key-state handling. I.e., creating a stateful mechanism which would work below the level of `usb_report_updater.c/applyKeyAction`. (Theoretically, such mechanim exists on my fork, but it currently uses the inherent statefulness of the paralelised macro engine, so it cannot be ported easily without heavier refactor or without merging significant part of my fork. Another way would be to implement it somewhere aside (or refactor my code) and keep track of the keys as part of the layer stack.)

Of course, the simplest solution is to simply declare the offending mapping as forbidden on agent side. And (of course) I am not a fan of such solution. In any case I don't feel very inclined about digging into the "legacy" layer switching mechanisms myself.

**Comment by sribst** [comment]
Trully sorry for my bad english and the mistake it brought

**Comment by kareltucek** [comment]
No problem, none of us is a native speaker ;-).

**Comment by mondalaci** [comment]
Thanks for the clarification, @kareltucek! I fully agree that the current layer switching mechanism should be implemented in a more general manner. Let's continue this in the referenced firmware issue. I don't have time for this right now, but want to dig into it later. I don't want to make the already existing mapping options more limited.
