### ISSUE TITLE
infinte secondary functions?

### ISSUE THREAD

**Issue by jsarbour** [UltimateHackingKeyboard/agent#974]
Why do keys only have one secondary function available with one modifier? I have 5 or 6 modifiers, why can't I map more things to them?

**Comment by luteijn** [comment]
There are only eight modifiers (shift, control, alt and super, each in a left and right version). These are used in the USB protocol spoken between the keyboard and OS. 
There are only four layers per keymap. These are used only by the keyboard to help decide what to send to the OS. 

Secondary function is just a way to make a key work one way when pressed and released and some other way when held.

You'll have to think in several 'planes' to really get the UHK, which is made more difficult because the separation isn't always 100% clean between things like hardware, firmware, OS, scancode, keycode, key, symbol, layer, keymap etc. Especially the word 'key' is very fuzzy...

**Comment by jsarbour** [comment]
Thanks for the insight. I see how hard you lot have worked to bring something so incredible to the market, I'll try and understand more before spamming you with issues.

**Comment by kareltucek** [comment]
In other words

- if you press a `key` which has no secondary role bound - then the keyboard sends `key`'s primary action (when the `key` is pressed). 
- if you press a `key` which has a secondary role bound and then release it without pressing another key in between - then the keyboard sends `key`'s primary action (but this time it does so when the `key` is *released*). 
- if you press a `key` which has a `modifier` as a secondary role and then press `another key` before releasing `key` - then the keyboard sends the `modifier` plus `another key`'s primary action  .
- if you press a `key` which has `layer` as a secondary role and then press `another key` before releasing `key` -  then the keyboard switches into the `layer` and then sends the primary action of the `another key` (as it is bound on the layer).

I will oppose Luteijn's statements - I think that the concepts are not hard to understand, the only thing you need to understand is that *modifiers* are one thing and *layers* are another thing. They work independent of each other and have nothing to do with each other.
- *Modifiers* are regular keys which are sent to the computer. 
- *Layers* are in fact simple "keymaps" (in the semantical meaning of word "keymap").
- *Keymaps* and *layers* are more or less the same thing, except that in UHK, a *keymap* is a higher-level construct which groups four simple "keymaps" (which are called *layers*) into one working unit.
